// JavaScript Document
$(document).ready(function(){
	XULITHONGTINTHEMES();
	XULITHONGTINHINHANH();
	XULITHONGTINBANG1();
	XuLiTinHieu();
	PushBaiViet1();
});

var WebsiteName ="Đam mê Hàng Không";
var SLOGAN = "Chấp cánh giấc mơ bay";
var TieuDeChuyenMuc = "Ảnh Hàng Không - Vietjet Air";

var HotPic1_address = "../Picture/IMG_0746.jpg";
var HotPic2_address = "../Picture/IMG_3803.jpg";
var HotPic3_address = "../Picture/IMG_2345.jpg";
var HotPic4_address = "../Picture/IMG_7515.jpg";
var AdvertisingPic  = "../Picture/AdvertiseHomePage.jpg";
var BannerVJ_address ="../Picture/Banner Vietjet.jpg";

var Tau1_Reg = "VN-A650"; var Tau1_AircraftType="Airbus 320-214(WL)";var Tau1_Config = "Y180"; var Tau1_Day="02/2015"; var Tau1_Age="5.2";
var Tau2_Reg = "VN-A655"; var Tau2_AircraftType="Airbus 320-214(WL)";var Tau2_Config = "Y180"; var Tau2_Day="03/2015"; var Tau2_Age="5.2";
var Tau3_Reg = "VN-A656"; var Tau3_AircraftType="Airbus A320-214(WL)";var Tau3_Config = "Y180"; var Tau3_Day="05/2015"; var Tau3_Age="5.0";
var Tau4_Reg = "VN-A658"; var Tau4_AircraftType="Airbus A320-214(WL)";var Tau4_Config = "Y180"; var Tau4_Day="11/2014"; var Tau4_Age="5.5";
var Tau5_Reg = "VN-A662"; var Tau5_AircraftType="Airbus A320-214(WL)";var Tau5_Config = "Y180"; var Tau5_Day="09/2015"; var Tau5_Age="4.6";
var Tau6_Reg = "VN-A663"; var Tau6_AircraftType="Airbus A320-214(WL)";var Tau6_Config = "Y180"; var Tau6_Day="10/2015"; var Tau6_Age="4.6";
var Tau7_Reg = "VN-A666"; var Tau7_AircraftType="Airbus 320-214";var Tau7_Config = "Y180"; var Tau7_Day="11/2011"; var Tau7_Age="11.3";
var Tau8_Reg = "VN-A668"; var Tau8_AircraftType="Airbus 320-214";var Tau8_Config = "Y180"; var Tau8_Day="12/2011"; var Tau8_Age="11.2";
var Tau9_Reg = "VN-A669"; var Tau9_AircraftType="Airbus 320-214";var Tau9_Config = "Y180"; var Tau9_Day="12/2011"; var Tau9_Age="10.6";
var Tau10_Reg = "VN-A671"; var Tau10_AircraftType="Airbus A320-214(WL)";var Tau10_Config = "Y180"; var Tau10_Day="02/2016"; var Tau10_Age="4.2";
var Tau11_Reg = "VN-A672"; var Tau11_AircraftType="Airbus A320-214(WL)";var Tau11_Config = "Y180"; var Tau11_Day="03/2016"; var Tau11_Age="4.2";
var Tau12_Reg = "VN-A675"; var Tau12_AircraftType="Airbus A320-214(WL)";var Tau12_Config = "Y180"; var Tau12_Day="06/2016"; var Tau12_Age="3.9";
var Tau13_Reg = "VN-A676"; var Tau13_AircraftType="Airbus A320-214(WL)";var Tau13_Config = "Y180"; var Tau13_Day="06/2016"; var Tau13_Age="3.9";
var Tau14_Reg = "VN-A678"; var Tau14_AircraftType="Airbus A320-214(WL)";var Tau14_Config = "Y180"; var Tau14_Day="03/2014"; var Tau14_Age="6.1";
var Tau15_Reg = "VN-A682"; var Tau15_AircraftType="Airbus A320-214(WL)";var Tau15_Config = "Y180"; var Tau15_Day="09/2013"; var Tau15_Age="6.7";
var Tau16_Reg = "VN-A686"; var Tau16_AircraftType="Airbus A320-214(WL)";var Tau16_Config = "Y180"; var Tau16_Day="10/2013"; var Tau16_Age="6.5";
var Tau17_Reg = "VN-A689"; var Tau17_AircraftType="Airbus 320-214";var Tau17_Config = "Y180"; var Tau17_Day="11/2012"; var Tau17_Age="10.3";
var Tau18_Reg = "VN-A690"; var Tau18_AircraftType="Airbus 320-214";var Tau18_Config = "Y180"; var Tau18_Day="05/2014"; var Tau18_Age="9.6";
var Tau19_Reg = "VN-A691"; var Tau19_AircraftType="Airbus 320-214";var Tau19_Config = "Y180"; var Tau19_Day="05/2014"; var Tau19_Age="9.5";
var Tau20_Reg = "VN-A695"; var Tau20_AircraftType="Airbus 320-214";var Tau20_Config = "Y180"; var Tau20_Day="10/2014"; var Tau20_Age="11.6";
var Tau21_Reg = "VN-A696"; var Tau21_AircraftType="Airbus A320-214(WL)";var Tau21_Config = "Y180"; var Tau21_Day="09/2014"; var Tau21_Age="5.6";
var Tau22_Reg = "VN-A699"; var Tau22_AircraftType="Airbus A320-214";var Tau22_Config = "Y180"; var Tau22_Day="01/2013"; var Tau22_Age="10.3";
var Tau23_Reg = "VN-A522"; var Tau23_AircraftType="Airbus A321-211(WL)";var Tau23_Config = "Y220"; var Tau23_Day="01/2020"; var Tau23_Age="4.9";

var Tau24_Reg = "VN-A532"; var Tau24_AircraftType="Airbus A321-211(WL)";var Tau24_Config = "Y220"; var Tau24_Day="12/2019"; var Tau24_Age="5.1";
var Tau25_Reg = "VN-A535"; var Tau25_AircraftType="Airbus A321-211(WL)";var Tau25_Config = "Y220"; var Tau25_Day="01/2020"; var Tau25_Age="4.2";
var Tau26_Reg = "VN-A541"; var Tau26_AircraftType="Airbus A321-211(WL)";var Tau26_Config = "Y220"; var Tau26_Day="01/2020"; var Tau26_Age="4.2";
var Tau27_Reg = "VN-A542"; var Tau27_AircraftType="Airbus A321-211(WL)";var Tau27_Config = "Y220"; var Tau27_Day="12/2019"; var Tau27_Age="4.1";
var Tau28_Reg = "VN-A544"; var Tau28_AircraftType="Airbus A321-211(WL)";var Tau28_Config = "Y220"; var Tau28_Day="01/2020"; var Tau28_Age="4.1";
var Tau29_Reg = "VN-A627"; var Tau29_AircraftType="Airbus A321-211(WL)";var Tau29_Config = "Y230"; var Tau29_Day="11/2018"; var Tau29_Age="1.5";
var Tau30_Reg = "VN-A628"; var Tau30_AircraftType="Airbus A321-211(WL)";var Tau30_Config = "Y230"; var Tau30_Day="11/2018"; var Tau30_Age="1.4";
var Tau31_Reg = "VN-A629"; var Tau31_AircraftType="Airbus A321-211(WL)";var Tau31_Config = "Y230"; var Tau31_Day="12/2018"; var Tau31_Age="1.4";
var Tau32_Reg = "VN-A630"; var Tau32_AircraftType="Airbus A321-211(WL)";var Tau32_Config = "Y230"; var Tau32_Day="04/2017"; var Tau32_Age="3.0";
var Tau33_Reg = "VN-A631"; var Tau33_AircraftType="Airbus A321-211(WL)";var Tau33_Config = "Y230"; var Tau33_Day="05/2017"; var Tau33_Age="3.0";
var Tau34_Reg = "VN-A632"; var Tau34_AircraftType="Airbus A321-211(WL)";var Tau34_Config = "Y230"; var Tau34_Day="10/2017"; var Tau34_Age="2.6";
var Tau35_Reg = "VN-A633"; var Tau35_AircraftType="Airbus A321-211(WL)";var Tau35_Config = "Y230"; var Tau35_Day="10/2017"; var Tau35_Age="2.5";
var Tau36_Reg = "VN-A634"; var Tau36_AircraftType="Airbus A321-211(WL)";var Tau36_Config = "Y230"; var Tau36_Day="11/2017"; var Tau36_Age="2.4";
var Tau37_Reg = "VN-A635"; var Tau37_AircraftType="Airbus A321-211(WL)";var Tau37_Config = "Y230"; var Tau37_Day="11/2017"; var Tau37_Age="2.5";
var Tau38_Reg = "VN-A636"; var Tau38_AircraftType="Airbus A321-211(WL)";var Tau38_Config = "Y230"; var Tau38_Day="12/2017"; var Tau38_Age="2.4";
var Tau39_Reg = "VN-A637"; var Tau39_AircraftType="Airbus A321-211(WL)";var Tau39_Config = "Y230"; var Tau39_Day="12/2017"; var Tau39_Age="2.4";
var Tau40_Reg = "VN-A639"; var Tau40_AircraftType="Airbus A321-211(WL)";var Tau40_Config = "Y230"; var Tau40_Day="12/2017"; var Tau40_Age="2.4";
var Tau40_Reg = "VN-A640"; var Tau40_AircraftType="Airbus A321-211(WL)";var Tau40_Config = "Y230"; var Tau40_Day="05/2017"; var Tau40_Age="3.0";
var Tau41_Reg = "VN-A641"; var Tau41_AircraftType="Airbus A321-211(WL)";var Tau41_Config = "Y230"; var Tau41_Day="05/2017"; var Tau41_Age="2.9";
var Tau42_Reg = "VN-A642"; var Tau42_AircraftType="Airbus A321-211(WL)";var Tau42_Config = "Y230"; var Tau42_Day="06/2017"; var Tau42_Age="2.9";
var Tau43_Reg = "VN-A643"; var Tau43_AircraftType="Airbus A321-211(WL)";var Tau43_Config = "Y230"; var Tau43_Day="11/2017"; var Tau43_Age="2.5";
var Tau44_Reg = "VN-A644"; var Tau44_AircraftType="Airbus A321-211(WL)";var Tau44_Config = "Y230"; var Tau44_Day="12/2017"; var Tau44_Age="2.4";
var Tau45_Reg = "VN-A645"; var Tau45_AircraftType="Airbus A321-211(WL)";var Tau45_Config = "Y230"; var Tau45_Day="11/2017"; var Tau45_Age="2.4";
var Tau46_Reg = "VN-A647"; var Tau46_AircraftType="Airbus A321-211(WL)";var Tau46_Config = "Y230"; var Tau46_Day="01/2018"; var Tau46_Age="2.3";

var Tau47_Reg = "VN-A648"; var Tau47_AircraftType="Airbus A321-211(WL)";var Tau47_Config = "Y230"; var Tau47_Day="01/2018"; var Tau47_Age="2.3";
var Tau48_Reg = "VN-A649"; var Tau48_AircraftType="Airbus A321-211(WL)";var Tau48_Config = "Y230"; var Tau48_Day="02/2018"; var Tau48_Age="2.2";
var Tau49_Reg = "VN-A651"; var Tau49_AircraftType="Airbus A321-211(WL)";var Tau49_Config = "Y220"; var Tau49_Day="03/2015"; var Tau49_Age="7.5";
var Tau50_Reg = "VN-A657"; var Tau50_AircraftType="Airbus A321-211(WL)";var Tau50_Config = "Y230"; var Tau50_Day="03/2018"; var Tau50_Age="2.1";
var Tau51_Reg = "VN-A661"; var Tau51_AircraftType="Airbus A321-211(WL)";var Tau51_Config = "Y230"; var Tau51_Day="12/2018"; var Tau51_Age="1.3";
var Tau52_Reg = "VN-A667"; var Tau52_AircraftType="Airbus A321-211(WL)";var Tau52_Config = "Y230"; var Tau52_Day="01/2016"; var Tau52_Age="4.7";
var Tau53_Reg = "VN-A670"; var Tau53_AircraftType="Airbus A321-211(WL)";var Tau53_Config = "Y230"; var Tau53_Day="12/2018"; var Tau53_Age="1.3";
var Tau54_Reg = "VN-A673"; var Tau54_AircraftType="Airbus A321-211(WL)";var Tau54_Config = "Y230"; var Tau54_Day="05/2016"; var Tau54_Age="3.9";
var Tau55_Reg = "VN-A677"; var Tau55_AircraftType="Airbus A321-211(WL)";var Tau55_Config = "Y230"; var Tau55_Day="07/2016"; var Tau55_Age="3.8";
var Tau56_Reg = "VN-A683"; var Tau56_AircraftType="Airbus A321-211(WL)";var Tau56_Config = "Y230"; var Tau56_Day="08/2016"; var Tau56_Age="3.7";
var Tau57_Reg = "VN-A684"; var Tau57_AircraftType="Airbus A321-211(WL)";var Tau57_Config = "Y230"; var Tau57_Day="10/2016"; var Tau57_Age="3.5";
var Tau58_Reg = "VN-A685"; var Tau58_AircraftType="Airbus A321-211(WL)";var Tau58_Config = "Y230"; var Tau58_Day="11/2016"; var Tau58_Age="3.4";
var Tau59_Reg = "VN-A687"; var Tau59_AircraftType="Airbus A321-211(WL)";var Tau59_Config = "Y230"; var Tau59_Day="12/2016"; var Tau59_Age="3.3";
var Tau60_Reg = "VN-A698"; var Tau60_AircraftType="Airbus A321-211(WL)";var Tau60_Config = "Y230"; var Tau60_Day="08/2018"; var Tau60_Age="1.7";
var Tau61_Reg = "VN-A520"; var Tau61_AircraftType="Airbus A321-271NX";var Tau61_Config = "Y240"; var Tau61_Day="09/2019"; var Tau61_Age="0.6";
var Tau62_Reg = "VN-A521"; var Tau62_AircraftType="Airbus A321-271NX";var Tau62_Config = "Y240"; var Tau62_Day="12/2019"; var Tau62_Age="0.3";
var Tau63_Reg = "VN-A523"; var Tau63_AircraftType="Airbus A321-271NX";var Tau63_Config = ""; var Tau63_Day="On Order"; var Tau63_Age="";
var Tau64_Reg = "VN-A524"; var Tau64_AircraftType="Airbus A321-271NX";var Tau64_Config = ""; var Tau64_Day="On Order"; var Tau64_Age="";
var Tau65_Reg = "VN-A531"; var Tau65_AircraftType="Airbus A321-271NX";var Tau65_Config = "Y240"; var Tau65_Day="11/2019"; var Tau65_Age="0.4";
var Tau66_Reg = "VN-A540"; var Tau66_AircraftType="Airbus A321-271N";var Tau66_Config = ""; var Tau66_Day="Due"; var Tau66_Age="4.1";
var Tau67_Reg = "VN-A600"; var Tau67_AircraftType="Airbus A321-271N";var Tau67_Config = "Y230"; var Tau67_Day="04/2019"; var Tau67_Age="1.1";
var Tau68_Reg = "VN-A607"; var Tau68_AircraftType="Airbus A321-271N";var Tau68_Config = "Y230"; var Tau68_Day="05/2019"; var Tau68_Age="0.9";
var Tau69_Reg = "VN-A626"; var Tau69_AircraftType="Airbus A321-271N";var Tau69_Config = "Y230"; var Tau69_Day="07/2019"; var Tau69_Age="0.8";

var Tau70_Reg = "VN-A646"; var Tau70_AircraftType="Airbus A321-271N";var Tau70_Config = "Y230"; var Tau70_Day="12/2017"; var Tau70_Age="2.3";
var Tau71_Reg = "VN-A652"; var Tau71_AircraftType="Airbus A321-271N";var Tau71_Config = "Y230"; var Tau71_Day="12/2018"; var Tau71_Age="1.3";
var Tau72_Reg = "VN-A653"; var Tau72_AircraftType="Airbus A321-271N";var Tau72_Config = "Y230"; var Tau72_Day="11/2018"; var Tau72_Age="1.6";
var Tau73_Reg = "VN-A654"; var Tau73_AircraftType="Airbus A321-271N";var Tau73_Config = "Y230"; var Tau73_Day="08/2018"; var Tau73_Age="1.7";
var Tau74_Reg = "VN-A674"; var Tau74_AircraftType="Airbus A321-271N";var Tau74_Config = "Y230"; var Tau74_Day="08/2018"; var Tau74_Age="1.7";
var Tau75_Reg = "VN-A693"; var Tau75_AircraftType="Airbus A321-271N";var Tau75_Config = "Y230"; var Tau75_Day="04/2019"; var Tau75_Age="1.2";
var Tau76_Reg = "VN-A694"; var Tau76_AircraftType="Airbus A321-271N";var Tau76_Config = "Y230"; var Tau76_Day="12/2018"; var Tau76_Age="1.4";
var Tau77_Reg = "VN-A697"; var Tau77_AircraftType="Airbus A321-271N";var Tau77_Config = "Y230"; var Tau77_Day="11/2018"; var Tau77_Age="1.4";

var Tau78_Reg = "VN-A"; var Tau78_AircraftType="";var Tau78_Config = ""; var Tau78_Day=""; var Tau78_Age="";
var Tau79_Reg = "VN-A"; var Tau79_AircraftType="";var Tau79_Config = ""; var Tau79_Day=""; var Tau79_Age="";
var Tau80_Reg = "VN-A"; var Tau80_AircraftType="";var Tau80_Config = ""; var Tau80_Day=""; var Tau80_Age="";
var Tau81_Reg = "VN-A"; var Tau81_AircraftType="";var Tau81_Config = ""; var Tau81_Day=""; var Tau81_Age="";
var Tau82_Reg = "VN-A"; var Tau82_AircraftType="";var Tau82_Config = ""; var Tau82_Day=""; var Tau82_Age="";
var Tau83_Reg = "VN-A"; var Tau83_AircraftType="";var Tau83_Config = ""; var Tau83_Day=""; var Tau83_Age="";
var Tau84_Reg = "VN-A"; var Tau84_AircraftType="";var Tau84_Config = ""; var Tau84_Day=""; var Tau84_Age="";
var Tau85_Reg = "VN-A"; var Tau85_AircraftType="";var Tau85_Config = ""; var Tau85_Day=""; var Tau85_Age="";
var Tau86_Reg = "VN-A"; var Tau86_AircraftType="";var Tau86_Config = ""; var Tau86_Day=""; var Tau86_Age="";
var Tau87_Reg = "VN-A"; var Tau87_AircraftType="";var Tau87_Config = ""; var Tau87_Day=""; var Tau87_Age="";
var Tau88_Reg = "VN-A"; var Tau88_AircraftType="";var Tau88_Config = ""; var Tau88_Day=""; var Tau88_Age="";
var Tau89_Reg = "VN-A"; var Tau89_AircraftType="";var Tau89_Config = ""; var Tau89_Day=""; var Tau89_Age="";
var Tau90_Reg = "VN-A"; var Tau90_AircraftType="";var Tau90_Config = ""; var Tau90_Day=""; var Tau90_Age="";
var Tau91_Reg = "VN-A"; var Tau91_AircraftType="";var Tau91_Config = ""; var Tau91_Day=""; var Tau91_Age="";
var Tau92_Reg = "VN-A"; var Tau92_AircraftType="";var Tau92_Config = ""; var Tau92_Day=""; var Tau92_Age="";

var AHK1_address = "../Picture/Waiting_Pic.jpg";
var AHK2_address = "../Picture/Waiting_Pic.jpg";
var AHK3_address = "../Picture/Waiting_Pic.jpg";
var AHK4_address = "../Picture/Waiting_Pic.jpg";
var AHK5_address = "../Picture/Waiting_Pic.jpg";
var AHK6_address = "../Picture/Waiting_Pic.jpg";
var AHK7_address = "../Picture/Waiting_Pic.jpg";
var AHK8_address = "../Picture/Waiting_Pic.jpg";
var AHK9_address = "../Picture/Waiting_Pic.jpg";
var AHK10_address = "../Picture/Waiting_Pic.jpg";
var AHK11_address = "../Picture/Waiting_Pic.jpg";
var AHK12_address = "../Picture/Waiting_Pic.jpg";
var AHK13_address = "../Picture/Waiting_Pic.jpg";
var AHK14_address = "../Picture/Waiting_Pic.jpg";
var AHK15_address = "../Picture/Waiting_Pic.jpg";
var AHK16_address = "../Picture/Waiting_Pic.jpg";
var AHK17_address = "../Picture/Waiting_Pic.jpg";
var AHK18_address = "../Picture/Waiting_Pic.jpg";
var AHK19_address = "../Picture/Waiting_Pic.jpg";
var AHK20_address = "../Picture/Waiting_Pic.jpg";
var AHK21_address = "../Picture/Waiting_Pic.jpg";
var AHK22_address = "../Picture/Waiting_Pic.jpg";
var AHK23_address = "../Picture/Waiting_Pic.jpg";
var AHK24_address = "../Picture/Waiting_Pic.jpg";


var AHK1Info = "Vietjet Air <br> Thông tin tàu bay ";
var AHK2Info = "Vietjet Air <br> Thông tin tàu bay ";
var AHK3Info = "Vietjet Air <br> Thông tin tàu bay ";
var AHK4Info = "Vietjet Air <br> Thông tin tàu bay ";
var AHK5Info = "Vietjet Air <br> Thông tin tàu bay ";
var AHK6Info = "Vietjet Air <br> Thông tin tàu bay ";
var AHK7Info = "Vietjet Air <br> Thông tin tàu bay ";
var AHK8Info = "Vietjet Air <br> Thông tin tàu bay ";
var AHK9Info = "Vietjet Air <br> Thông tin tàu bay ";
var AHK10Info = "Vietjet Air<br> Thông tin tàu bay ";
var AHK11Info = "Vietjet Air <br> Thông tin tàu bay ";
var AHK12Info = "Vietjet Air <br> Thông tin tàu bay ";
var AHK13Info = "Vietjet Air <br> Thông tin tàu bay ";
var AHK14Info = "Vietjet Air <br> Thông tin tàu bay ";
var AHK15Info = "Vietjet Air <br> Thông tin tàu bay ";
var AHK16Info = "Vietjet Air <br> Thông tin tàu bay ";
var AHK17Info = "Vietjet Air <br> Thông tin tàu bay ";
var AHK18Info = "Vietjet Air <br> Thông tin tàu bay ";
var AHK19Info = "Vietjet Air <br> Thông tin tàu bay ";
var AHK20Info = "Vietjet Air <br> Thông tin tàu bay ";
var AHK21Info = "Vietjet Air <br> Thông tin tàu bay ";
var AHK22Info = "Vietjet Air <br> Thông tin tàu bay ";
var AHK23Info = "Vietjet Air <br> Thông tin tàu bay ";
var AHK24Info = "Vietjet Air <br> Thông tin tàu bay ";



function XULITHONGTINTHEMES()
{
	document.getElementById('WebsiteName').innerHTML=WebsiteName;
	document.getElementById('Slogan').innerHTML=SLOGAN;
	document.getElementById('TieuDeChuyenMuc').innerHTML=TieuDeChuyenMuc;
}

function XULITHONGTINHINHANH()
{
	$('#HotPic1').attr("src",HotPic1_address);
	$('#HotPic2').attr("src",HotPic2_address);
	$('#HotPic3').attr("src",HotPic3_address);
	$('#HotPic4').attr("src",HotPic4_address);
	$('#AdvertisingPic').attr("src",AdvertisingPic);
	$('#Banner_Vietjet').attr("src",BannerVJ_address);
}

function XULITHONGTINBANG1()
{
	document.getElementById('Tau1_Reg').innerHTML=Tau1_Reg;
	document.getElementById('Tau1_AircraftType').innerHTML=Tau1_AircraftType;
	document.getElementById('Tau1_Config').innerHTML=Tau1_Config;
	document.getElementById('Tau1_Day').innerHTML=Tau1_Day;
	document.getElementById('Tau1_Age').innerHTML=Tau1_Age;
	document.getElementById('Tau2_Reg').innerHTML=Tau2_Reg;
	document.getElementById('Tau2_AircraftType').innerHTML=Tau2_AircraftType;
	document.getElementById('Tau2_Config').innerHTML=Tau2_Config;
	document.getElementById('Tau2_Day').innerHTML=Tau2_Day;
	document.getElementById('Tau2_Age').innerHTML=Tau2_Age;
	document.getElementById('Tau3_Reg').innerHTML=Tau3_Reg;
	document.getElementById('Tau3_AircraftType').innerHTML=Tau3_AircraftType;
	document.getElementById('Tau3_Config').innerHTML=Tau3_Config;
	document.getElementById('Tau3_Day').innerHTML=Tau3_Day;
	document.getElementById('Tau3_Age').innerHTML=Tau3_Age;
	document.getElementById('Tau4_Reg').innerHTML=Tau4_Reg;
	document.getElementById('Tau4_AircraftType').innerHTML=Tau4_AircraftType;
	document.getElementById('Tau4_Config').innerHTML=Tau4_Config;
	document.getElementById('Tau4_Day').innerHTML=Tau4_Day;
	document.getElementById('Tau4_Age').innerHTML=Tau4_Age;
	document.getElementById('Tau5_Reg').innerHTML=Tau5_Reg;
	document.getElementById('Tau5_AircraftType').innerHTML=Tau5_AircraftType;
	document.getElementById('Tau5_Config').innerHTML=Tau5_Config;
	document.getElementById('Tau5_Day').innerHTML=Tau5_Day;
	document.getElementById('Tau5_Age').innerHTML=Tau5_Age;
	document.getElementById('Tau6_Reg').innerHTML=Tau6_Reg;
	document.getElementById('Tau6_AircraftType').innerHTML=Tau6_AircraftType;
	document.getElementById('Tau6_Config').innerHTML=Tau6_Config;
	document.getElementById('Tau6_Day').innerHTML=Tau6_Day;
	document.getElementById('Tau6_Age').innerHTML=Tau6_Age;
	document.getElementById('Tau7_Reg').innerHTML=Tau7_Reg;
	document.getElementById('Tau7_AircraftType').innerHTML=Tau7_AircraftType;
	document.getElementById('Tau7_Config').innerHTML=Tau7_Config;
	document.getElementById('Tau7_Day').innerHTML=Tau7_Day;
	document.getElementById('Tau7_Age').innerHTML=Tau7_Age;
	document.getElementById('Tau8_Reg').innerHTML=Tau8_Reg;
	document.getElementById('Tau8_AircraftType').innerHTML=Tau8_AircraftType;
	document.getElementById('Tau8_Config').innerHTML=Tau8_Config;
	document.getElementById('Tau8_Day').innerHTML=Tau8_Day;
	document.getElementById('Tau8_Age').innerHTML=Tau8_Age;
	document.getElementById('Tau9_Reg').innerHTML=Tau9_Reg;
	document.getElementById('Tau9_AircraftType').innerHTML=Tau9_AircraftType;
	document.getElementById('Tau9_Config').innerHTML=Tau9_Config;
	document.getElementById('Tau9_Day').innerHTML=Tau9_Day;
	document.getElementById('Tau9_Age').innerHTML=Tau9_Age;
	document.getElementById('Tau10_Reg').innerHTML=Tau10_Reg;
	document.getElementById('Tau10_AircraftType').innerHTML=Tau10_AircraftType;
	document.getElementById('Tau10_Config').innerHTML=Tau10_Config;
	document.getElementById('Tau10_Day').innerHTML=Tau10_Day;
	document.getElementById('Tau10_Age').innerHTML=Tau10_Age;
	document.getElementById('Tau11_Reg').innerHTML=Tau11_Reg;
	document.getElementById('Tau11_AircraftType').innerHTML=Tau11_AircraftType;
	document.getElementById('Tau11_Config').innerHTML=Tau11_Config;
	document.getElementById('Tau11_Day').innerHTML=Tau11_Day;
	document.getElementById('Tau11_Age').innerHTML=Tau11_Age;
	document.getElementById('Tau12_Reg').innerHTML=Tau12_Reg;
	document.getElementById('Tau12_AircraftType').innerHTML=Tau12_AircraftType;
	document.getElementById('Tau12_Config').innerHTML=Tau12_Config;
	document.getElementById('Tau12_Day').innerHTML=Tau12_Day;
	document.getElementById('Tau12_Age').innerHTML=Tau12_Age;
	document.getElementById('Tau13_Reg').innerHTML=Tau13_Reg;
	document.getElementById('Tau13_AircraftType').innerHTML=Tau13_AircraftType;
	document.getElementById('Tau13_Config').innerHTML=Tau13_Config;
	document.getElementById('Tau13_Day').innerHTML=Tau13_Day;
	document.getElementById('Tau13_Age').innerHTML=Tau13_Age;
	document.getElementById('Tau14_Reg').innerHTML=Tau14_Reg;
	document.getElementById('Tau14_AircraftType').innerHTML=Tau14_AircraftType;
	document.getElementById('Tau14_Config').innerHTML=Tau14_Config;
	document.getElementById('Tau14_Day').innerHTML=Tau14_Day;
	document.getElementById('Tau14_Age').innerHTML=Tau14_Age;
	document.getElementById('Tau15_Reg').innerHTML=Tau15_Reg;
	document.getElementById('Tau15_AircraftType').innerHTML=Tau15_AircraftType;
	document.getElementById('Tau15_Config').innerHTML=Tau15_Config;
	document.getElementById('Tau15_Day').innerHTML=Tau15_Day;
	document.getElementById('Tau15_Age').innerHTML=Tau15_Age;
	document.getElementById('Tau16_Reg').innerHTML=Tau16_Reg;
	document.getElementById('Tau16_AircraftType').innerHTML=Tau16_AircraftType;
	document.getElementById('Tau16_Config').innerHTML=Tau16_Config;
	document.getElementById('Tau16_Day').innerHTML=Tau16_Day;
	document.getElementById('Tau16_Age').innerHTML=Tau16_Age;
	document.getElementById('Tau17_Reg').innerHTML=Tau17_Reg;
	document.getElementById('Tau17_AircraftType').innerHTML=Tau17_AircraftType;
	document.getElementById('Tau17_Config').innerHTML=Tau17_Config;
	document.getElementById('Tau17_Day').innerHTML=Tau17_Day;
	document.getElementById('Tau17_Age').innerHTML=Tau17_Age;
	document.getElementById('Tau18_Reg').innerHTML=Tau18_Reg;
	document.getElementById('Tau18_AircraftType').innerHTML=Tau18_AircraftType;
	document.getElementById('Tau18_Config').innerHTML=Tau18_Config;
	document.getElementById('Tau18_Day').innerHTML=Tau18_Day;
	document.getElementById('Tau18_Age').innerHTML=Tau18_Age;
	document.getElementById('Tau19_Reg').innerHTML=Tau19_Reg;
	document.getElementById('Tau19_AircraftType').innerHTML=Tau19_AircraftType;
	document.getElementById('Tau19_Config').innerHTML=Tau19_Config;
	document.getElementById('Tau19_Day').innerHTML=Tau19_Day;
	document.getElementById('Tau19_Age').innerHTML=Tau19_Age;
	document.getElementById('Tau20_Reg').innerHTML=Tau20_Reg;
	document.getElementById('Tau20_AircraftType').innerHTML=Tau20_AircraftType;
	document.getElementById('Tau20_Config').innerHTML=Tau20_Config;
	document.getElementById('Tau20_Day').innerHTML=Tau20_Day;
	document.getElementById('Tau20_Age').innerHTML=Tau20_Age;
	document.getElementById('Tau21_Reg').innerHTML=Tau21_Reg;
	document.getElementById('Tau21_AircraftType').innerHTML=Tau21_AircraftType;
	document.getElementById('Tau21_Config').innerHTML=Tau21_Config;
	document.getElementById('Tau21_Day').innerHTML=Tau21_Day;
	document.getElementById('Tau21_Age').innerHTML=Tau21_Age;
	document.getElementById('Tau22_Reg').innerHTML=Tau22_Reg;
	document.getElementById('Tau22_AircraftType').innerHTML=Tau22_AircraftType;
	document.getElementById('Tau22_Config').innerHTML=Tau22_Config;
	document.getElementById('Tau22_Day').innerHTML=Tau22_Day;
	document.getElementById('Tau22_Age').innerHTML=Tau22_Age;
	document.getElementById('Tau23_Reg').innerHTML=Tau23_Reg;
	document.getElementById('Tau23_AircraftType').innerHTML=Tau23_AircraftType;
	document.getElementById('Tau23_Config').innerHTML=Tau23_Config;
	document.getElementById('Tau23_Day').innerHTML=Tau23_Day;
	document.getElementById('Tau23_Age').innerHTML=Tau23_Age;
	document.getElementById('Button1T').style.backgroundColor='white';
	document.getElementById('Button1T').style.color='black';
	document.getElementById('Button2T').style.backgroundColor='black';
	document.getElementById('Button2T').style.color='white';
	document.getElementById('Button3T').style.backgroundColor='black';
	document.getElementById('Button3T').style.color='white';
	document.getElementById('Button4T').style.backgroundColor='black';
	document.getElementById('Button4T').style.color='white';
}

function XULITHONGTINBANG2()
{
	document.getElementById('Tau1_Reg').innerHTML=Tau24_Reg;
	document.getElementById('Tau1_AircraftType').innerHTML=Tau24_AircraftType;
	document.getElementById('Tau1_Config').innerHTML=Tau24_Config;
	document.getElementById('Tau1_Day').innerHTML=Tau24_Day;
	document.getElementById('Tau1_Age').innerHTML=Tau24_Age;
	document.getElementById('Tau2_Reg').innerHTML=Tau25_Reg;
	document.getElementById('Tau2_AircraftType').innerHTML=Tau25_AircraftType;
	document.getElementById('Tau2_Config').innerHTML=Tau25_Config;
	document.getElementById('Tau2_Day').innerHTML=Tau25_Day;
	document.getElementById('Tau2_Age').innerHTML=Tau25_Age;
	document.getElementById('Tau3_Reg').innerHTML=Tau26_Reg;
	document.getElementById('Tau3_AircraftType').innerHTML=Tau26_AircraftType;
	document.getElementById('Tau3_Config').innerHTML=Tau26_Config;
	document.getElementById('Tau3_Day').innerHTML=Tau26_Day;
	document.getElementById('Tau3_Age').innerHTML=Tau26_Age;
	document.getElementById('Tau4_Reg').innerHTML=Tau27_Reg;
	document.getElementById('Tau4_AircraftType').innerHTML=Tau27_AircraftType;
	document.getElementById('Tau4_Config').innerHTML=Tau27_Config;
	document.getElementById('Tau4_Day').innerHTML=Tau27_Day;
	document.getElementById('Tau4_Age').innerHTML=Tau27_Age;
	document.getElementById('Tau5_Reg').innerHTML=Tau28_Reg;
	document.getElementById('Tau5_AircraftType').innerHTML=Tau28_AircraftType;
	document.getElementById('Tau5_Config').innerHTML=Tau28_Config;
	document.getElementById('Tau5_Day').innerHTML=Tau28_Day;
	document.getElementById('Tau5_Age').innerHTML=Tau28_Age;
	document.getElementById('Tau6_Reg').innerHTML=Tau29_Reg;
	document.getElementById('Tau6_AircraftType').innerHTML=Tau29_AircraftType;
	document.getElementById('Tau6_Config').innerHTML=Tau29_Config;
	document.getElementById('Tau6_Day').innerHTML=Tau29_Day;
	document.getElementById('Tau6_Age').innerHTML=Tau29_Age;
	document.getElementById('Tau7_Reg').innerHTML=Tau30_Reg;
	document.getElementById('Tau7_AircraftType').innerHTML=Tau30_AircraftType;
	document.getElementById('Tau7_Config').innerHTML=Tau30_Config;
	document.getElementById('Tau7_Day').innerHTML=Tau30_Day;
	document.getElementById('Tau7_Age').innerHTML=Tau30_Age;
	document.getElementById('Tau8_Reg').innerHTML=Tau31_Reg;
	document.getElementById('Tau8_AircraftType').innerHTML=Tau31_AircraftType;
	document.getElementById('Tau8_Config').innerHTML=Tau31_Config;
	document.getElementById('Tau8_Day').innerHTML=Tau31_Day;
	document.getElementById('Tau8_Age').innerHTML=Tau31_Age;
	document.getElementById('Tau9_Reg').innerHTML=Tau32_Reg;
	document.getElementById('Tau9_AircraftType').innerHTML=Tau32_AircraftType;
	document.getElementById('Tau9_Config').innerHTML=Tau32_Config;
	document.getElementById('Tau9_Day').innerHTML=Tau32_Day;
	document.getElementById('Tau9_Age').innerHTML=Tau32_Age;
	document.getElementById('Tau10_Reg').innerHTML=Tau33_Reg;
	document.getElementById('Tau10_AircraftType').innerHTML=Tau33_AircraftType;
	document.getElementById('Tau10_Config').innerHTML=Tau33_Config;
	document.getElementById('Tau10_Day').innerHTML=Tau33_Day;
	document.getElementById('Tau10_Age').innerHTML=Tau33_Age;
	document.getElementById('Tau11_Reg').innerHTML=Tau34_Reg;
	document.getElementById('Tau11_AircraftType').innerHTML=Tau34_AircraftType;
	document.getElementById('Tau11_Config').innerHTML=Tau34_Config;
	document.getElementById('Tau11_Day').innerHTML=Tau34_Day;
	document.getElementById('Tau11_Age').innerHTML=Tau34_Age;
	document.getElementById('Tau12_Reg').innerHTML=Tau35_Reg;
	document.getElementById('Tau12_AircraftType').innerHTML=Tau35_AircraftType;
	document.getElementById('Tau12_Config').innerHTML=Tau35_Config;
	document.getElementById('Tau12_Day').innerHTML=Tau35_Day;
	document.getElementById('Tau12_Age').innerHTML=Tau35_Age;
	document.getElementById('Tau13_Reg').innerHTML=Tau36_Reg;
	document.getElementById('Tau13_AircraftType').innerHTML=Tau36_AircraftType;
	document.getElementById('Tau13_Config').innerHTML=Tau36_Config;
	document.getElementById('Tau13_Day').innerHTML=Tau36_Day;
	document.getElementById('Tau13_Age').innerHTML=Tau36_Age;
	document.getElementById('Tau14_Reg').innerHTML=Tau37_Reg;
	document.getElementById('Tau14_AircraftType').innerHTML=Tau37_AircraftType;
	document.getElementById('Tau14_Config').innerHTML=Tau37_Config;
	document.getElementById('Tau14_Day').innerHTML=Tau37_Day;
	document.getElementById('Tau14_Age').innerHTML=Tau37_Age;
	document.getElementById('Tau15_Reg').innerHTML=Tau38_Reg;
	document.getElementById('Tau15_AircraftType').innerHTML=Tau38_AircraftType;
	document.getElementById('Tau15_Config').innerHTML=Tau38_Config;
	document.getElementById('Tau15_Day').innerHTML=Tau38_Day;
	document.getElementById('Tau15_Age').innerHTML=Tau38_Age;
	document.getElementById('Tau16_Reg').innerHTML=Tau39_Reg;
	document.getElementById('Tau16_AircraftType').innerHTML=Tau39_AircraftType;
	document.getElementById('Tau16_Config').innerHTML=Tau39_Config;
	document.getElementById('Tau16_Day').innerHTML=Tau39_Day;
	document.getElementById('Tau16_Age').innerHTML=Tau39_Age;
	document.getElementById('Tau17_Reg').innerHTML=Tau40_Reg;
	document.getElementById('Tau17_AircraftType').innerHTML=Tau40_AircraftType;
	document.getElementById('Tau17_Config').innerHTML=Tau40_Config;
	document.getElementById('Tau17_Day').innerHTML=Tau40_Day;
	document.getElementById('Tau17_Age').innerHTML=Tau40_Age;
	document.getElementById('Tau18_Reg').innerHTML=Tau41_Reg;
	document.getElementById('Tau18_AircraftType').innerHTML=Tau41_AircraftType;
	document.getElementById('Tau18_Config').innerHTML=Tau41_Config;
	document.getElementById('Tau18_Day').innerHTML=Tau41_Day;
	document.getElementById('Tau18_Age').innerHTML=Tau41_Age;
	document.getElementById('Tau19_Reg').innerHTML=Tau42_Reg;
	document.getElementById('Tau19_AircraftType').innerHTML=Tau42_AircraftType;
	document.getElementById('Tau19_Config').innerHTML=Tau42_Config;
	document.getElementById('Tau19_Day').innerHTML=Tau42_Day;
	document.getElementById('Tau19_Age').innerHTML=Tau42_Age;
	document.getElementById('Tau20_Reg').innerHTML=Tau43_Reg;
	document.getElementById('Tau20_AircraftType').innerHTML=Tau43_AircraftType;
	document.getElementById('Tau20_Config').innerHTML=Tau43_Config;
	document.getElementById('Tau20_Day').innerHTML=Tau43_Day;
	document.getElementById('Tau20_Age').innerHTML=Tau43_Age;
	document.getElementById('Tau21_Reg').innerHTML=Tau44_Reg;
	document.getElementById('Tau21_AircraftType').innerHTML=Tau44_AircraftType;
	document.getElementById('Tau21_Config').innerHTML=Tau44_Config;
	document.getElementById('Tau21_Day').innerHTML=Tau44_Day;
	document.getElementById('Tau21_Age').innerHTML=Tau44_Age;
	document.getElementById('Tau22_Reg').innerHTML=Tau45_Reg;
	document.getElementById('Tau22_AircraftType').innerHTML=Tau45_AircraftType;
	document.getElementById('Tau22_Config').innerHTML=Tau45_Config;
	document.getElementById('Tau22_Day').innerHTML=Tau45_Day;
	document.getElementById('Tau22_Age').innerHTML=Tau45_Age;
	document.getElementById('Tau23_Reg').innerHTML=Tau46_Reg;
	document.getElementById('Tau23_AircraftType').innerHTML=Tau46_AircraftType;
	document.getElementById('Tau23_Config').innerHTML=Tau46_Config;
	document.getElementById('Tau23_Day').innerHTML=Tau46_Day;
	document.getElementById('Tau23_Age').innerHTML=Tau46_Age;
	document.getElementById('Button1T').style.backgroundColor='black';
	document.getElementById('Button1T').style.color='white';
	document.getElementById('Button2T').style.backgroundColor='white';
	document.getElementById('Button2T').style.color='black';
	document.getElementById('Button3T').style.backgroundColor='black';
	document.getElementById('Button3T').style.color='white';
	document.getElementById('Button4T').style.backgroundColor='black';
	document.getElementById('Button4T').style.color='white';
}

function XULITHONGTINBANG3()
{
	document.getElementById('Tau1_Reg').innerHTML=Tau47_Reg;
	document.getElementById('Tau1_AircraftType').innerHTML=Tau47_AircraftType;
	document.getElementById('Tau1_Config').innerHTML=Tau47_Config;
	document.getElementById('Tau1_Day').innerHTML=Tau47_Day;
	document.getElementById('Tau1_Age').innerHTML=Tau47_Age;
	document.getElementById('Tau2_Reg').innerHTML=Tau48_Reg;
	document.getElementById('Tau2_AircraftType').innerHTML=Tau48_AircraftType;
	document.getElementById('Tau2_Config').innerHTML=Tau48_Config;
	document.getElementById('Tau2_Day').innerHTML=Tau48_Day;
	document.getElementById('Tau2_Age').innerHTML=Tau48_Age;
	document.getElementById('Tau3_Reg').innerHTML=Tau49_Reg;
	document.getElementById('Tau3_AircraftType').innerHTML=Tau49_AircraftType;
	document.getElementById('Tau3_Config').innerHTML=Tau49_Config;
	document.getElementById('Tau3_Day').innerHTML=Tau49_Day;
	document.getElementById('Tau3_Age').innerHTML=Tau49_Age;
	document.getElementById('Tau4_Reg').innerHTML=Tau50_Reg;
	document.getElementById('Tau4_AircraftType').innerHTML=Tau50_AircraftType;
	document.getElementById('Tau4_Config').innerHTML=Tau50_Config;
	document.getElementById('Tau4_Day').innerHTML=Tau50_Day;
	document.getElementById('Tau4_Age').innerHTML=Tau50_Age;
	document.getElementById('Tau5_Reg').innerHTML=Tau51_Reg;
	document.getElementById('Tau5_AircraftType').innerHTML=Tau51_AircraftType;
	document.getElementById('Tau5_Config').innerHTML=Tau51_Config;
	document.getElementById('Tau5_Day').innerHTML=Tau51_Day;
	document.getElementById('Tau5_Age').innerHTML=Tau51_Age;
	document.getElementById('Tau6_Reg').innerHTML=Tau52_Reg;
	document.getElementById('Tau6_AircraftType').innerHTML=Tau52_AircraftType;
	document.getElementById('Tau6_Config').innerHTML=Tau52_Config;
	document.getElementById('Tau6_Day').innerHTML=Tau52_Day;
	document.getElementById('Tau6_Age').innerHTML=Tau52_Age;
	document.getElementById('Tau7_Reg').innerHTML=Tau53_Reg;
	document.getElementById('Tau7_AircraftType').innerHTML=Tau53_AircraftType;
	document.getElementById('Tau7_Config').innerHTML=Tau53_Config;
	document.getElementById('Tau7_Day').innerHTML=Tau53_Day;
	document.getElementById('Tau7_Age').innerHTML=Tau53_Age;
	document.getElementById('Tau8_Reg').innerHTML=Tau54_Reg;
	document.getElementById('Tau8_AircraftType').innerHTML=Tau54_AircraftType;
	document.getElementById('Tau8_Config').innerHTML=Tau54_Config;
	document.getElementById('Tau8_Day').innerHTML=Tau54_Day;
	document.getElementById('Tau8_Age').innerHTML=Tau54_Age;
	document.getElementById('Tau9_Reg').innerHTML=Tau55_Reg;
	document.getElementById('Tau9_AircraftType').innerHTML=Tau55_AircraftType;
	document.getElementById('Tau9_Config').innerHTML=Tau55_Config;
	document.getElementById('Tau9_Day').innerHTML=Tau55_Day;
	document.getElementById('Tau9_Age').innerHTML=Tau55_Age;
	document.getElementById('Tau10_Reg').innerHTML=Tau56_Reg;
	document.getElementById('Tau10_AircraftType').innerHTML=Tau56_AircraftType;
	document.getElementById('Tau10_Config').innerHTML=Tau56_Config;
	document.getElementById('Tau10_Day').innerHTML=Tau56_Day;
	document.getElementById('Tau10_Age').innerHTML=Tau56_Age;
	document.getElementById('Tau11_Reg').innerHTML=Tau57_Reg;
	document.getElementById('Tau11_AircraftType').innerHTML=Tau57_AircraftType;
	document.getElementById('Tau11_Config').innerHTML=Tau57_Config;
	document.getElementById('Tau11_Day').innerHTML=Tau57_Day;
	document.getElementById('Tau11_Age').innerHTML=Tau57_Age;
	document.getElementById('Tau12_Reg').innerHTML=Tau58_Reg;
	document.getElementById('Tau12_AircraftType').innerHTML=Tau58_AircraftType;
	document.getElementById('Tau12_Config').innerHTML=Tau58_Config;
	document.getElementById('Tau12_Day').innerHTML=Tau58_Day;
	document.getElementById('Tau12_Age').innerHTML=Tau58_Age;
	document.getElementById('Tau13_Reg').innerHTML=Tau59_Reg;
	document.getElementById('Tau13_AircraftType').innerHTML=Tau59_AircraftType;
	document.getElementById('Tau13_Config').innerHTML=Tau59_Config;
	document.getElementById('Tau13_Day').innerHTML=Tau59_Day;
	document.getElementById('Tau13_Age').innerHTML=Tau59_Age;
	document.getElementById('Tau14_Reg').innerHTML=Tau60_Reg;
	document.getElementById('Tau14_AircraftType').innerHTML=Tau60_AircraftType;
	document.getElementById('Tau14_Config').innerHTML=Tau60_Config;
	document.getElementById('Tau14_Day').innerHTML=Tau60_Day;
	document.getElementById('Tau14_Age').innerHTML=Tau60_Age;
	document.getElementById('Tau15_Reg').innerHTML=Tau61_Reg;
	document.getElementById('Tau15_AircraftType').innerHTML=Tau61_AircraftType;
	document.getElementById('Tau15_Config').innerHTML=Tau61_Config;
	document.getElementById('Tau15_Day').innerHTML=Tau61_Day;
	document.getElementById('Tau15_Age').innerHTML=Tau61_Age;
	document.getElementById('Tau16_Reg').innerHTML=Tau62_Reg;
	document.getElementById('Tau16_AircraftType').innerHTML=Tau62_AircraftType;
	document.getElementById('Tau16_Config').innerHTML=Tau62_Config;
	document.getElementById('Tau16_Day').innerHTML=Tau62_Day;
	document.getElementById('Tau16_Age').innerHTML=Tau62_Age;
	document.getElementById('Tau17_Reg').innerHTML=Tau63_Reg;
	document.getElementById('Tau17_AircraftType').innerHTML=Tau63_AircraftType;
	document.getElementById('Tau17_Config').innerHTML=Tau63_Config;
	document.getElementById('Tau17_Day').innerHTML=Tau63_Day;
	document.getElementById('Tau17_Age').innerHTML=Tau63_Age;
	document.getElementById('Tau18_Reg').innerHTML=Tau64_Reg;
	document.getElementById('Tau18_AircraftType').innerHTML=Tau64_AircraftType;
	document.getElementById('Tau18_Config').innerHTML=Tau64_Config;
	document.getElementById('Tau18_Day').innerHTML=Tau64_Day;
	document.getElementById('Tau18_Age').innerHTML=Tau64_Age;
	document.getElementById('Tau19_Reg').innerHTML=Tau65_Reg;
	document.getElementById('Tau19_AircraftType').innerHTML=Tau65_AircraftType;
	document.getElementById('Tau19_Config').innerHTML=Tau65_Config;
	document.getElementById('Tau19_Day').innerHTML=Tau65_Day;
	document.getElementById('Tau19_Age').innerHTML=Tau65_Age;
	document.getElementById('Tau20_Reg').innerHTML=Tau66_Reg;
	document.getElementById('Tau20_AircraftType').innerHTML=Tau66_AircraftType;
	document.getElementById('Tau20_Config').innerHTML=Tau66_Config;
	document.getElementById('Tau20_Day').innerHTML=Tau66_Day;
	document.getElementById('Tau20_Age').innerHTML=Tau66_Age;
	document.getElementById('Tau21_Reg').innerHTML=Tau67_Reg;
	document.getElementById('Tau21_AircraftType').innerHTML=Tau67_AircraftType;
	document.getElementById('Tau21_Config').innerHTML=Tau67_Config;
	document.getElementById('Tau21_Day').innerHTML=Tau67_Day;
	document.getElementById('Tau21_Age').innerHTML=Tau67_Age;
	document.getElementById('Tau22_Reg').innerHTML=Tau68_Reg;
	document.getElementById('Tau22_AircraftType').innerHTML=Tau68_AircraftType;
	document.getElementById('Tau22_Config').innerHTML=Tau68_Config;
	document.getElementById('Tau22_Day').innerHTML=Tau68_Day;
	document.getElementById('Tau22_Age').innerHTML=Tau68_Age;
	document.getElementById('Tau23_Reg').innerHTML=Tau69_Reg;
	document.getElementById('Tau23_AircraftType').innerHTML=Tau69_AircraftType;
	document.getElementById('Tau23_Config').innerHTML=Tau69_Config;
	document.getElementById('Tau23_Day').innerHTML=Tau69_Day;
	document.getElementById('Tau23_Age').innerHTML=Tau69_Age;
	document.getElementById('Button1T').style.backgroundColor='black';
	document.getElementById('Button1T').style.color='white';
	document.getElementById('Button2T').style.backgroundColor='black';
	document.getElementById('Button2T').style.color='white';
	document.getElementById('Button3T').style.backgroundColor='white';
	document.getElementById('Button3T').style.color='black';
	document.getElementById('Button4T').style.backgroundColor='black';
	document.getElementById('Button4T').style.color='white';
}

function XULITHONGTINBANG4()
{
	document.getElementById('Tau1_Reg').innerHTML=Tau70_Reg;
	document.getElementById('Tau1_AircraftType').innerHTML=Tau70_AircraftType;
	document.getElementById('Tau1_Config').innerHTML=Tau70_Config;
	document.getElementById('Tau1_Day').innerHTML=Tau70_Day;
	document.getElementById('Tau1_Age').innerHTML=Tau70_Age;
	document.getElementById('Tau2_Reg').innerHTML=Tau71_Reg;
	document.getElementById('Tau2_AircraftType').innerHTML=Tau71_AircraftType;
	document.getElementById('Tau2_Config').innerHTML=Tau71_Config;
	document.getElementById('Tau2_Day').innerHTML=Tau71_Day;
	document.getElementById('Tau2_Age').innerHTML=Tau71_Age;
	document.getElementById('Tau3_Reg').innerHTML=Tau72_Reg;
	document.getElementById('Tau3_AircraftType').innerHTML=Tau72_AircraftType;
	document.getElementById('Tau3_Config').innerHTML=Tau72_Config;
	document.getElementById('Tau3_Day').innerHTML=Tau72_Day;
	document.getElementById('Tau3_Age').innerHTML=Tau72_Age;
	document.getElementById('Tau4_Reg').innerHTML=Tau73_Reg;
	document.getElementById('Tau4_AircraftType').innerHTML=Tau73_AircraftType;
	document.getElementById('Tau4_Config').innerHTML=Tau73_Config;
	document.getElementById('Tau4_Day').innerHTML=Tau73_Day;
	document.getElementById('Tau4_Age').innerHTML=Tau73_Age;
	document.getElementById('Tau5_Reg').innerHTML=Tau74_Reg;
	document.getElementById('Tau5_AircraftType').innerHTML=Tau74_AircraftType;
	document.getElementById('Tau5_Config').innerHTML=Tau74_Config;
	document.getElementById('Tau5_Day').innerHTML=Tau74_Day;
	document.getElementById('Tau5_Age').innerHTML=Tau74_Age;
	document.getElementById('Tau6_Reg').innerHTML=Tau75_Reg;
	document.getElementById('Tau6_AircraftType').innerHTML=Tau75_AircraftType;
	document.getElementById('Tau6_Config').innerHTML=Tau75_Config;
	document.getElementById('Tau6_Day').innerHTML=Tau75_Day;
	document.getElementById('Tau6_Age').innerHTML=Tau75_Age;
	document.getElementById('Tau7_Reg').innerHTML=Tau76_Reg;
	document.getElementById('Tau7_AircraftType').innerHTML=Tau76_AircraftType;
	document.getElementById('Tau7_Config').innerHTML=Tau76_Config;
	document.getElementById('Tau7_Day').innerHTML=Tau76_Day;
	document.getElementById('Tau7_Age').innerHTML=Tau76_Age;
	document.getElementById('Tau8_Reg').innerHTML=Tau77_Reg;
	document.getElementById('Tau8_AircraftType').innerHTML=Tau77_AircraftType;
	document.getElementById('Tau8_Config').innerHTML=Tau77_Config;
	document.getElementById('Tau8_Day').innerHTML=Tau77_Day;
	document.getElementById('Tau8_Age').innerHTML=Tau77_Age;
	document.getElementById('Tau9_Reg').innerHTML=Tau78_Reg;
	document.getElementById('Tau9_AircraftType').innerHTML=Tau78_AircraftType;
	document.getElementById('Tau9_Config').innerHTML=Tau78_Config;
	document.getElementById('Tau9_Day').innerHTML=Tau78_Day;
	document.getElementById('Tau9_Age').innerHTML=Tau78_Age;
	document.getElementById('Tau10_Reg').innerHTML=Tau79_Reg;
	document.getElementById('Tau10_AircraftType').innerHTML=Tau79_AircraftType;
	document.getElementById('Tau10_Config').innerHTML=Tau79_Config;
	document.getElementById('Tau10_Day').innerHTML=Tau79_Day;
	document.getElementById('Tau10_Age').innerHTML=Tau79_Age;
	document.getElementById('Tau11_Reg').innerHTML=Tau80_Reg;
	document.getElementById('Tau11_AircraftType').innerHTML=Tau80_AircraftType;
	document.getElementById('Tau11_Config').innerHTML=Tau80_Config;
	document.getElementById('Tau11_Day').innerHTML=Tau80_Day;
	document.getElementById('Tau11_Age').innerHTML=Tau80_Age;
	document.getElementById('Tau12_Reg').innerHTML=Tau81_Reg;
	document.getElementById('Tau12_AircraftType').innerHTML=Tau81_AircraftType;
	document.getElementById('Tau12_Config').innerHTML=Tau81_Config;
	document.getElementById('Tau12_Day').innerHTML=Tau81_Day;
	document.getElementById('Tau12_Age').innerHTML=Tau81_Age;
	document.getElementById('Tau13_Reg').innerHTML=Tau82_Reg;
	document.getElementById('Tau13_AircraftType').innerHTML=Tau82_AircraftType;
	document.getElementById('Tau13_Config').innerHTML=Tau82_Config;
	document.getElementById('Tau13_Day').innerHTML=Tau82_Day;
	document.getElementById('Tau13_Age').innerHTML=Tau82_Age;
	document.getElementById('Tau14_Reg').innerHTML=Tau83_Reg;
	document.getElementById('Tau14_AircraftType').innerHTML=Tau83_AircraftType;
	document.getElementById('Tau14_Config').innerHTML=Tau83_Config;
	document.getElementById('Tau14_Day').innerHTML=Tau83_Day;
	document.getElementById('Tau14_Age').innerHTML=Tau83_Age;
	document.getElementById('Tau15_Reg').innerHTML=Tau84_Reg;
	document.getElementById('Tau15_AircraftType').innerHTML=Tau84_AircraftType;
	document.getElementById('Tau15_Config').innerHTML=Tau84_Config;
	document.getElementById('Tau15_Day').innerHTML=Tau84_Day;
	document.getElementById('Tau15_Age').innerHTML=Tau84_Age;
	document.getElementById('Tau16_Reg').innerHTML=Tau85_Reg;
	document.getElementById('Tau16_AircraftType').innerHTML=Tau85_AircraftType;
	document.getElementById('Tau16_Config').innerHTML=Tau85_Config;
	document.getElementById('Tau16_Day').innerHTML=Tau85_Day;
	document.getElementById('Tau16_Age').innerHTML=Tau85_Age;
	document.getElementById('Tau17_Reg').innerHTML=Tau86_Reg;
	document.getElementById('Tau17_AircraftType').innerHTML=Tau86_AircraftType;
	document.getElementById('Tau17_Config').innerHTML=Tau86_Config;
	document.getElementById('Tau17_Day').innerHTML=Tau86_Day;
	document.getElementById('Tau17_Age').innerHTML=Tau86_Age;
	document.getElementById('Tau18_Reg').innerHTML=Tau87_Reg;
	document.getElementById('Tau18_AircraftType').innerHTML=Tau87_AircraftType;
	document.getElementById('Tau18_Config').innerHTML=Tau87_Config;
	document.getElementById('Tau18_Day').innerHTML=Tau87_Day;
	document.getElementById('Tau18_Age').innerHTML=Tau87_Age;
	document.getElementById('Tau19_Reg').innerHTML=Tau88_Reg;
	document.getElementById('Tau19_AircraftType').innerHTML=Tau88_AircraftType;
	document.getElementById('Tau19_Config').innerHTML=Tau88_Config;
	document.getElementById('Tau19_Day').innerHTML=Tau88_Day;
	document.getElementById('Tau19_Age').innerHTML=Tau88_Age;
	document.getElementById('Tau20_Reg').innerHTML=Tau89_Reg;
	document.getElementById('Tau20_AircraftType').innerHTML=Tau89_AircraftType;
	document.getElementById('Tau20_Config').innerHTML=Tau89_Config;
	document.getElementById('Tau20_Day').innerHTML=Tau89_Day;
	document.getElementById('Tau20_Age').innerHTML=Tau89_Age;
	document.getElementById('Tau21_Reg').innerHTML=Tau90_Reg;
	document.getElementById('Tau21_AircraftType').innerHTML=Tau90_AircraftType;
	document.getElementById('Tau21_Config').innerHTML=Tau90_Config;
	document.getElementById('Tau21_Day').innerHTML=Tau90_Day;
	document.getElementById('Tau21_Age').innerHTML=Tau90_Age;
	document.getElementById('Tau22_Reg').innerHTML=Tau91_Reg;
	document.getElementById('Tau22_AircraftType').innerHTML=Tau91_AircraftType;
	document.getElementById('Tau22_Config').innerHTML=Tau91_Config;
	document.getElementById('Tau22_Day').innerHTML=Tau91_Day;
	document.getElementById('Tau22_Age').innerHTML=Tau91_Age;
	document.getElementById('Tau23_Reg').innerHTML=Tau92_Reg;
	document.getElementById('Tau23_AircraftType').innerHTML=Tau92_AircraftType;
	document.getElementById('Tau23_Config').innerHTML=Tau92_Config;
	document.getElementById('Tau23_Day').innerHTML=Tau92_Day;
	document.getElementById('Tau23_Age').innerHTML=Tau92_Age;
	document.getElementById('Button1T').style.backgroundColor='black';
	document.getElementById('Button1T').style.color='white';
	document.getElementById('Button2T').style.backgroundColor='black';
	document.getElementById('Button2T').style.color='white';
	document.getElementById('Button3T').style.backgroundColor='black';
	document.getElementById('Button3T').style.color='white';
	document.getElementById('Button4T').style.backgroundColor='white';
	document.getElementById('Button4T').style.color='black';
}

function XuLiTinHieu(){
	var Event1 = document.getElementById('ButtonThongTin1');
	Event1.onclick = Changelayer2;
	var Event2 = document.getElementById('ButtonThongTin2');
	Event2.onclick = Changelayer1;
	var ButtonEvent1 = document.getElementById('Button1');
	ButtonEvent1.onclick = PushBaiViet1;
	var ButtonEvent2 = document.getElementById('Button2');
	ButtonEvent2.onclick = PushBaiViet2;
	var ButtonEvent3 = document.getElementById('Button3');
	ButtonEvent3.onclick = PushBaiViet3;
	var ButtonEvent4 = document.getElementById('Button4');
	ButtonEvent4.onclick = PushBaiViet4;
	var ButtonEvent5 = document.getElementById('Button1T');
	ButtonEvent5.onclick = XULITHONGTINBANG1;
	var ButtonEvent6 = document.getElementById('Button2T');
	ButtonEvent6.onclick = XULITHONGTINBANG2;
	var ButtonEvent7 = document.getElementById('Button3T');
	ButtonEvent7.onclick = XULITHONGTINBANG3;
	var ButtonEvent4 = document.getElementById('Button4T');
	ButtonEvent4.onclick = XULITHONGTINBANG4;
}

function Changelayer1(){
	document.getElementById('AnhVietjetArea').style.display='none';
	document.getElementById('TieuDeNoiDungTrang').style.display='inherit';
	document.getElementById('ButtonThongTin2').style.display='none';
}
function Changelayer2(){
	document.getElementById('AnhVietjetArea').style.display='inherit';
	document.getElementById('TieuDeNoiDungTrang').style.display='none';
	document.getElementById('ButtonThongTin2').style.display='inherit';
}

function PushBaiViet1(){
	$('#AHK1').attr("src",AHK1_address);
	$('#AHK2').attr("src",AHK2_address);
	$('#AHK3').attr("src",AHK3_address);
	$('#AHK4').attr("src",AHK4_address);
	$('#AHK5').attr("src",AHK5_address);
	$('#AHK6').attr("src",AHK6_address);
	document.getElementById('PicInfo1').innerHTML = AHK1Info;
	document.getElementById('PicInfo2').innerHTML = AHK2Info;
	document.getElementById('PicInfo3').innerHTML = AHK3Info;
	document.getElementById('PicInfo4').innerHTML = AHK4Info;
	document.getElementById('PicInfo5').innerHTML = AHK5Info;
	document.getElementById('PicInfo6').innerHTML = AHK6Info;
	document.getElementById('Button1').style.backgroundColor='white';
	document.getElementById('Button1').style.color='black';
	document.getElementById('Button2').style.backgroundColor='black';
	document.getElementById('Button2').style.color='white';
	document.getElementById('Button3').style.backgroundColor='black';
	document.getElementById('Button3').style.color='white';
	document.getElementById('Button4').style.backgroundColor='black';
	document.getElementById('Button4').style.color='white';
}

function PushBaiViet2(){
	$('#AHK1').attr("src",AHK7_address);
	$('#AHK2').attr("src",AHK8_address);
	$('#AHK3').attr("src",AHK9_address);
	$('#AHK4').attr("src",AHK10_address);
	$('#AHK5').attr("src",AHK11_address);
	$('#AHK6').attr("src",AHK12_address);
	document.getElementById('PicInfo1').innerHTML = AHK7Info;
	document.getElementById('PicInfo2').innerHTML = AHK8Info;
	document.getElementById('PicInfo3').innerHTML = AHK9Info;
	document.getElementById('PicInfo4').innerHTML = AHK10Info;
	document.getElementById('PicInfo5').innerHTML = AHK11Info;
	document.getElementById('PicInfo6').innerHTML = AHK12Info;
	document.getElementById('Button1').style.backgroundColor='black';
	document.getElementById('Button1').style.color='white';
	document.getElementById('Button2').style.backgroundColor='white';
	document.getElementById('Button2').style.color='black';
	document.getElementById('Button3').style.backgroundColor='black';
	document.getElementById('Button3').style.color='white';
	document.getElementById('Button4').style.backgroundColor='black';
	document.getElementById('Button4').style.color='white';
}

function PushBaiViet3(){
	$('#AHK1').attr("src",AHK13_address);
	$('#AHK2').attr("src",AHK14_address);
	$('#AHK3').attr("src",AHK15_address);
	$('#AHK4').attr("src",AHK16_address);
	$('#AHK5').attr("src",AHK17_address);
	$('#AHK6').attr("src",AHK18_address);
	document.getElementById('PicInfo1').innerHTML = AHK13Info;
	document.getElementById('PicInfo2').innerHTML = AHK14Info;
	document.getElementById('PicInfo3').innerHTML = AHK15Info;
	document.getElementById('PicInfo4').innerHTML = AHK16Info;
	document.getElementById('PicInfo5').innerHTML = AHK17Info;
	document.getElementById('PicInfo6').innerHTML = AHK18Info;
	document.getElementById('Button1').style.backgroundColor='black';
	document.getElementById('Button1').style.color='white';
	document.getElementById('Button2').style.backgroundColor='black';
	document.getElementById('Button2').style.color='white';
	document.getElementById('Button3').style.backgroundColor='white';
	document.getElementById('Button3').style.color='black';
	document.getElementById('Button4').style.backgroundColor='black';
	document.getElementById('Button4').style.color='white';
}

function PushBaiViet4(){
	$('#AHK1').attr("src",AHK19_address);
	$('#AHK2').attr("src",AHK20_address);
	$('#AHK3').attr("src",AHK21_address);
	$('#AHK4').attr("src",AHK22_address);
	$('#AHK5').attr("src",AHK23_address);
	$('#AHK6').attr("src",AHK24_address);
	document.getElementById('PicInfo1').innerHTML = AHK19Info;
	document.getElementById('PicInfo2').innerHTML = AHK20Info;
	document.getElementById('PicInfo3').innerHTML = AHK21Info;
	document.getElementById('PicInfo4').innerHTML = AHK22Info;
	document.getElementById('PicInfo5').innerHTML = AHK23Info;
	document.getElementById('PicInfo6').innerHTML = AHK24Info;
	document.getElementById('Button1').style.backgroundColor='black';
	document.getElementById('Button1').style.color='white';
	document.getElementById('Button2').style.backgroundColor='black';
	document.getElementById('Button2').style.color='white';
	document.getElementById('Button3').style.backgroundColor='black';
	document.getElementById('Button3').style.color='white';
	document.getElementById('Button4').style.backgroundColor='white';
	document.getElementById('Button4').style.color='black';
}