// JavaScript Document
$(document).ready(function(){
	XULITHONGTINTHEMES();
	XULITHONGTINHINHANH();
	XULITHONGTINBANG1();
	XuLiTinHieu();
	PushBaiViet1();
});

var WebsiteName ="Đam mê Hàng Không";
var SLOGAN = "Chấp cánh giấc mơ bay";
var TieuDeChuyenMuc = "Ảnh Hàng Không - Vietnam Airlines";

var HotPic1_address = "../Picture/IMG_0746.jpg";
var HotPic2_address = "../Picture/IMG_3803.jpg";
var HotPic3_address = "../Picture/IMG_2345.jpg";
var HotPic4_address = "../Picture/IMG_7515.jpg";
var AdvertisingPic  = "../Picture/AdvertiseHomePage.jpg";
var BannerVNA_address ="../Picture/Banner VNA.jpg";

var Tau1_Reg = "VN-A322"; var Tau1_AircraftType="Airbus 321-200";var Tau1_Config = "C16Y168"; var Tau1_Day="05/2010"; var Tau1_Age="9.9";
var Tau2_Reg = "VN-A323"; var Tau2_AircraftType="Airbus 321-200";var Tau2_Config = "C16Y168"; var Tau2_Day="04/2011"; var Tau2_Age="9.1";
var Tau3_Reg = "VN-A324"; var Tau3_AircraftType="Airbus 321-200";var Tau3_Config = "C16Y168"; var Tau3_Day="05/2011"; var Tau3_Age="8.9";
var Tau4_Reg = "VN-A325"; var Tau4_AircraftType="Airbus 321-200";var Tau4_Config = "C16Y168"; var Tau4_Day="06/2011"; var Tau4_Age="8.9";
var Tau5_Reg = "VN-A326"; var Tau5_AircraftType="Airbus 321-200";var Tau5_Config = "C16Y168"; var Tau5_Day="07/2011"; var Tau5_Age="8.8";
var Tau6_Reg = "VN-A327"; var Tau6_AircraftType="Airbus 321-200";var Tau6_Config = "C16Y168"; var Tau6_Day="11/2013"; var Tau6_Age="8.7";
var Tau7_Reg = "VN-A329"; var Tau7_AircraftType="Airbus 321-200";var Tau7_Config = "C16Y168"; var Tau7_Day="11/2011"; var Tau7_Age="8.5";
var Tau8_Reg = "VN-A331"; var Tau8_AircraftType="Airbus 321-200";var Tau8_Config = "C16Y168"; var Tau8_Day="12/2011"; var Tau8_Age="8.4";
var Tau9_Reg = "VN-A332"; var Tau9_AircraftType="Airbus 321-200";var Tau9_Config = "C16Y168"; var Tau9_Day="12/2011"; var Tau9_Age="8.4";
var Tau10_Reg = "VN-A334"; var Tau10_AircraftType="Airbus 321-200";var Tau10_Config = "C16Y168"; var Tau10_Day="06/2012"; var Tau10_Age="7.9";
var Tau11_Reg = "VN-A335"; var Tau11_AircraftType="Airbus 321-200";var Tau11_Config = "C16Y168"; var Tau11_Day="08/2012"; var Tau11_Age="7.7";
var Tau12_Reg = "VN-A336"; var Tau12_AircraftType="Airbus 321-200";var Tau12_Config = "C16Y168"; var Tau12_Day="08/2012"; var Tau12_Age="7.7";
var Tau13_Reg = "VN-A338"; var Tau13_AircraftType="Airbus 321-200";var Tau13_Config = "C16Y168"; var Tau13_Day="08/2012"; var Tau13_Age="7.8";
var Tau14_Reg = "VN-A339"; var Tau14_AircraftType="Airbus 321-200";var Tau14_Config = "C16Y168"; var Tau14_Day="09/2012"; var Tau14_Age="7.7";
var Tau15_Reg = "VN-A344"; var Tau15_AircraftType="Airbus 321-200";var Tau15_Config = "C8Y195"; var Tau15_Day="07/2004"; var Tau15_Age="15.9";
var Tau16_Reg = "VN-A345"; var Tau16_AircraftType="Airbus 321-200";var Tau16_Config = "C16Y168"; var Tau16_Day="08/2016"; var Tau16_Age="15.9";
var Tau17_Reg = "VN-A348"; var Tau17_AircraftType="Airbus 321-200";var Tau17_Config = "C16Y168"; var Tau17_Day="11/2016"; var Tau17_Age="15.6";
var Tau18_Reg = "VN-A349"; var Tau18_AircraftType="Airbus 321-200";var Tau18_Config = "C16Y168"; var Tau18_Day="03/2017"; var Tau18_Age="15.0";
var Tau19_Reg = "VN-A350"; var Tau19_AircraftType="Airbus 321-200";var Tau19_Config = "C16Y168"; var Tau19_Day="01/2007"; var Tau19_Age="13.4";
var Tau20_Reg = "VN-A351"; var Tau20_AircraftType="Airbus 321-200";var Tau20_Config = "C16Y168"; var Tau20_Day="01/2014"; var Tau20_Age="13.3";
var Tau21_Reg = "VN-A352"; var Tau21_AircraftType="Airbus 321-200";var Tau21_Config = "C16Y168"; var Tau21_Day="02/2007"; var Tau21_Age="13.3";
var Tau22_Reg = "VN-A353"; var Tau22_AircraftType="Airbus 321-200";var Tau22_Config = "C16Y168"; var Tau22_Day="02/2007"; var Tau22_Age="13.2";
var Tau23_Reg = "VN-A354"; var Tau23_AircraftType="Airbus 321-200";var Tau23_Config = "C16Y168"; var Tau23_Day="07/2007"; var Tau23_Age="12.8";

var Tau24_Reg = "VN-A356"; var Tau24_AircraftType="Airbus 321-200";var Tau24_Config = "C16Y168"; var Tau24_Day="02/2020"; var Tau24_Age="12.4";
var Tau25_Reg = "VN-A357"; var Tau25_AircraftType="Airbus 321-200";var Tau25_Config = "C16Y168"; var Tau25_Day="01/2008"; var Tau25_Age="12.3";
var Tau26_Reg = "VN-A358"; var Tau26_AircraftType="Airbus 321-200";var Tau26_Config = "C16Y168"; var Tau26_Day="07/2008"; var Tau26_Age="11.7";
var Tau27_Reg = "VN-A359"; var Tau27_AircraftType="Airbus 321-200";var Tau27_Config = "C16Y168"; var Tau27_Day="12/2008"; var Tau27_Age="11.4";
var Tau28_Reg = "VN-A361"; var Tau28_AircraftType="Airbus 321-200";var Tau28_Config = "C16Y168"; var Tau28_Day="12/2009"; var Tau28_Age="10.8";
var Tau29_Reg = "VN-A362"; var Tau29_AircraftType="Airbus 321-200";var Tau29_Config = "C16Y168"; var Tau29_Day="12/2009"; var Tau29_Age="10.8";
var Tau30_Reg = "VN-A363"; var Tau30_AircraftType="Airbus 321-200";var Tau30_Config = "C16Y168"; var Tau30_Day="03/2010"; var Tau30_Age="10.2";
var Tau31_Reg = "VN-A365"; var Tau31_AircraftType="Airbus 321-200";var Tau31_Config = "C16Y168"; var Tau31_Day="03/2010"; var Tau31_Age="10.2";
var Tau32_Reg = "VN-A366"; var Tau32_AircraftType="Airbus 321-200";var Tau32_Config = "C16Y168"; var Tau32_Day="04/2010"; var Tau32_Age="10.0";
var Tau33_Reg = "VN-A367"; var Tau33_AircraftType="Airbus 321-200";var Tau33_Config = "C16Y168"; var Tau33_Day="05/2010"; var Tau33_Age="9.9";
var Tau34_Reg = "VN-A390"; var Tau34_AircraftType="Airbus 321-200";var Tau34_Config = "C16Y168"; var Tau34_Day="10/2012"; var Tau34_Age="7.6";
var Tau35_Reg = "VN-A392"; var Tau35_AircraftType="Airbus 321-200";var Tau35_Config = "C16Y168"; var Tau35_Day="10/2012"; var Tau35_Age="7.6";
var Tau36_Reg = "VN-A393"; var Tau36_AircraftType="Airbus 321-200";var Tau36_Config = "C16Y168"; var Tau36_Day="10/2012"; var Tau36_Age="7.5";
var Tau37_Reg = "VN-A395"; var Tau37_AircraftType="Airbus 321-200";var Tau37_Config = "C16Y168"; var Tau37_Day="12/2012"; var Tau37_Age="7.3";
var Tau38_Reg = "VN-A396"; var Tau38_AircraftType="Airbus 321-200";var Tau38_Config = "C16Y168"; var Tau38_Day="12/2012"; var Tau38_Age="7.4";
var Tau39_Reg = "VN-A397"; var Tau39_AircraftType="Airbus 321-200";var Tau39_Config = "C16Y168"; var Tau39_Day="12/2012"; var Tau39_Age="7.4";
var Tau40_Reg = "VN-A398"; var Tau40_AircraftType="Airbus 321-200";var Tau40_Config = "C16Y168"; var Tau40_Day="04/2016"; var Tau40_Age="7.3";
var Tau40_Reg = "VN-A399"; var Tau40_AircraftType="Airbus 321-200";var Tau40_Config = "C16Y168"; var Tau40_Day="01/2013"; var Tau40_Age="7.3";
var Tau41_Reg = "VN-A601"; var Tau41_AircraftType="Airbus 321-200";var Tau41_Config = "C16Y168"; var Tau41_Day="02/2013"; var Tau41_Age="7.2";
var Tau42_Reg = "VN-A602"; var Tau42_AircraftType="Airbus 321-200";var Tau42_Config = "C16Y168"; var Tau42_Day="03/2013"; var Tau42_Age="7.2";
var Tau43_Reg = "VN-A603"; var Tau43_AircraftType="Airbus 321-200";var Tau43_Config = "C16Y168"; var Tau43_Day="03/2013"; var Tau43_Age="7.1";
var Tau44_Reg = "VN-A604"; var Tau44_AircraftType="Airbus 321-200";var Tau44_Config = "C16Y168"; var Tau44_Day="04/2013"; var Tau44_Age="7.0";
var Tau45_Reg = "VN-A605"; var Tau45_AircraftType="Airbus 321-200";var Tau45_Config = "C16Y168"; var Tau45_Day="08/2013"; var Tau45_Age="6.8";
var Tau46_Reg = "VN-A606"; var Tau46_AircraftType="Airbus 321-200";var Tau46_Config = "C16Y168"; var Tau46_Day="08/2013"; var Tau46_Age="6.8";

var Tau47_Reg = "VN-A608"; var Tau47_AircraftType="Airbus 321-200";var Tau47_Config = "C16Y168"; var Tau47_Day="12/2013"; var Tau47_Age="6.3";
var Tau48_Reg = "VN-A609"; var Tau48_AircraftType="Airbus 321-200";var Tau48_Config = "C16Y168"; var Tau48_Day="02/2014"; var Tau48_Age="6.2";
var Tau49_Reg = "VN-A610"; var Tau49_AircraftType="Airbus 321-200";var Tau49_Config = "C16Y168"; var Tau49_Day="03/2014"; var Tau49_Age="6.2";
var Tau50_Reg = "VN-A611"; var Tau50_AircraftType="Airbus 321-200";var Tau50_Config = "C16Y168"; var Tau50_Day="09/2014"; var Tau50_Age="5.6";
var Tau51_Reg = "VN-A612"; var Tau51_AircraftType="Airbus 321-200";var Tau51_Config = "C16Y168"; var Tau51_Day="11/2014"; var Tau51_Age="5.5";
var Tau52_Reg = "VN-A613"; var Tau52_AircraftType="Airbus 321-200";var Tau52_Config = "C8Y195"; var Tau52_Day="08/2015"; var Tau52_Age="4.7";
var Tau53_Reg = "VN-A614"; var Tau53_AircraftType="Airbus 321-200";var Tau53_Config = "C8Y195"; var Tau53_Day="11/2015"; var Tau53_Age="4.5";
var Tau54_Reg = "VN-A615"; var Tau54_AircraftType="Airbus 321-200";var Tau54_Config = "C8Y195"; var Tau54_Day="12/2015"; var Tau54_Age="4.4";
var Tau55_Reg = "VN-A501"; var Tau55_AircraftType="Airbus 321Neo";var Tau55_Config = "C8Y195"; var Tau55_Day="12/2018"; var Tau55_Age="1.4";
var Tau56_Reg = "VN-A503"; var Tau56_AircraftType="Airbus 321Neo";var Tau56_Config = "C8Y195"; var Tau56_Day="05/2019"; var Tau56_Age="0.9";
var Tau57_Reg = "VN-A505"; var Tau57_AircraftType="Airbus 321Neo";var Tau57_Config = "C8Y195"; var Tau57_Day="09/2019"; var Tau57_Age="0.6";
var Tau58_Reg = "VN-A506"; var Tau58_AircraftType="Airbus 321Neo";var Tau58_Config = "C8Y195"; var Tau58_Day="11/2019"; var Tau58_Age="0.6";
var Tau59_Reg = "VN-A507"; var Tau59_AircraftType="Airbus 321Neo";var Tau59_Config = "C8Y195"; var Tau59_Day="10/2019"; var Tau59_Age="0.6";
var Tau60_Reg = "VN-A508"; var Tau60_AircraftType="Airbus 321Neo";var Tau60_Config = "C8Y195"; var Tau60_Day="12/2019"; var Tau60_Age="0.4";
var Tau61_Reg = "VN-A509"; var Tau61_AircraftType="Airbus 321Neo";var Tau61_Config = "C8Y195"; var Tau61_Day="01/2020"; var Tau61_Age="0.3";
var Tau62_Reg = "VN-A510"; var Tau62_AircraftType="Airbus 321Neo";var Tau62_Config = "C8Y195"; var Tau62_Day="12/2019"; var Tau62_Age="0.4";
var Tau63_Reg = "VN-A511"; var Tau63_AircraftType="Airbus 321Neo";var Tau63_Config = "C8Y195"; var Tau63_Day="12/2019"; var Tau63_Age="0.4";
var Tau64_Reg = "VN-A512"; var Tau64_AircraftType="Airbus 321Neo";var Tau64_Config = "C8Y195"; var Tau64_Day="12/2019"; var Tau64_Age="0.4";
var Tau65_Reg = "VN-A616"; var Tau65_AircraftType="Airbus 321Neo";var Tau65_Config = "C8Y195"; var Tau65_Day="04/2019"; var Tau65_Age="1.0";
var Tau66_Reg = "VN-A617"; var Tau66_AircraftType="Airbus 321Neo";var Tau66_Config = "C8Y195"; var Tau66_Day="11/2018"; var Tau66_Age="1.5";
var Tau67_Reg = "VN-A618"; var Tau67_AircraftType="Airbus 321Neo";var Tau67_Config = "C8Y195"; var Tau67_Day="11/2018"; var Tau67_Age="1.4";
var Tau68_Reg = "VN-A619"; var Tau68_AircraftType="Airbus 321Neo";var Tau68_Config = "C8Y195"; var Tau68_Day="01/2019"; var Tau68_Age="1.3";
var Tau69_Reg = "VN-A620"; var Tau69_AircraftType="Airbus 321Neo";var Tau69_Config = "C8Y195"; var Tau69_Day="05/2019"; var Tau69_Age="1.2";

var Tau70_Reg = "VN-A621"; var Tau70_AircraftType="Airbus 321Neo";var Tau70_Config = "C8Y195"; var Tau70_Day="02/2019"; var Tau70_Age="1.2";
var Tau71_Reg = "VN-A622"; var Tau71_AircraftType="Airbus 321Neo";var Tau71_Config = "C8Y195"; var Tau71_Day="04/2019"; var Tau71_Age="1.2";
var Tau72_Reg = "VN-A623"; var Tau72_AircraftType="Airbus 321Neo";var Tau72_Config = "C8Y195"; var Tau72_Day="04/2019"; var Tau72_Age="1.2";
var Tau73_Reg = "VN-A624"; var Tau73_AircraftType="Airbus 321Neo";var Tau73_Config = "C8Y195"; var Tau73_Day="04/2019"; var Tau73_Age="1.1";
var Tau74_Reg = "VN-A625"; var Tau74_AircraftType="Airbus 321Neo";var Tau74_Config = "C8Y195"; var Tau74_Day="07/2019"; var Tau74_Age="0.8";
var Tau75_Reg = ""; var Tau75_AircraftType="";var Tau75_Config = ""; var Tau75_Day=""; var Tau75_Age="";
var Tau76_Reg = "VN-A886"; var Tau76_AircraftType="Airbus 350-900";var Tau76_Config = "C29W45Y231"; var Tau76_Day="06/2015"; var Tau76_Age="4.9";
var Tau77_Reg = "VN-A887"; var Tau77_AircraftType="Airbus 350-900";var Tau77_Config = "C29W45Y231"; var Tau77_Day="09/2015"; var Tau77_Age="4.7";
var Tau78_Reg = "VN-A888"; var Tau78_AircraftType="Airbus 350-900";var Tau78_Config = "C29W45Y231"; var Tau78_Day="10/2015"; var Tau78_Age="4.6";
var Tau79_Reg = "VN-A889"; var Tau79_AircraftType="Airbus 350-900";var Tau79_Config = "C29W45Y231"; var Tau79_Day="12/2015"; var Tau79_Age="4.5";
var Tau80_Reg = "VN-A890"; var Tau80_AircraftType="Airbus 350-900";var Tau80_Config = "C29W36Y240"; var Tau80_Day="10/2016"; var Tau80_Age="3.5";
var Tau81_Reg = "VN-A891"; var Tau81_AircraftType="Airbus 350-900";var Tau81_Config = "C29W36Y240"; var Tau81_Day="12/2016"; var Tau81_Age="3.4";
var Tau82_Reg = "VN-A892"; var Tau82_AircraftType="Airbus 350-900";var Tau82_Config = "C29W36Y240"; var Tau82_Day="03/2017"; var Tau82_Age="3.2";
var Tau83_Reg = "VN-A893"; var Tau83_AircraftType="Airbus 350-900";var Tau83_Config = "C29W36Y240"; var Tau83_Day="08/2017"; var Tau83_Age="2.8";
var Tau84_Reg = "VN-A894"; var Tau84_AircraftType="Airbus 350-900";var Tau84_Config = "C29W36Y240"; var Tau84_Day="11/2017"; var Tau84_Age="2.5";
var Tau85_Reg = "VN-A895"; var Tau85_AircraftType="Airbus 350-900";var Tau85_Config = "C29W36Y240"; var Tau85_Day="12/2017"; var Tau85_Age="2.4";
var Tau86_Reg = "VN-A896"; var Tau86_AircraftType="Airbus 350-900";var Tau86_Config = "C29W36Y240"; var Tau86_Day="03/2018"; var Tau86_Age="2.2";
var Tau87_Reg = "VN-A897"; var Tau87_AircraftType="Airbus 350-900";var Tau87_Config = "C29W36Y240"; var Tau87_Day="04/2018"; var Tau87_Age="2.1";
var Tau88_Reg = "VN-A898"; var Tau88_AircraftType="Airbus 350-900";var Tau88_Config = "C29W36Y240"; var Tau88_Day="02/2019"; var Tau88_Age="1.2";
var Tau89_Reg = "VN-A899"; var Tau89_AircraftType="Airbus 350-900";var Tau89_Config = "C29W36Y240"; var Tau89_Day="05/2019"; var Tau89_Age="1.1";
var Tau90_Reg = "VN-A872"; var Tau90_AircraftType="Boeing 787-10 Dreamliner";var Tau90_Config = "C24Y343"; var Tau90_Day="08/2019"; var Tau90_Age="0.7";
var Tau91_Reg = "VN-A873"; var Tau91_AircraftType="Boeing 787-10 Dreamliner";var Tau91_Config = "C24Y343"; var Tau91_Day="10/2019"; var Tau91_Age="0.5";
var Tau92_Reg = "VN-A874"; var Tau92_AircraftType="Boeing 787-10 Dreamliner";var Tau92_Config = "C24Y343"; var Tau92_Day="03/2020"; var Tau92_Age="0.2";

var Tau93_Reg = "VN-A879"; var Tau93_AircraftType="Boeing 787-10 Dreamliner";var Tau93_Config = "C24Y343"; var Tau93_Day="08/2019"; var Tau93_Age="0.7";
var Tau94_Reg = "VN-A861"; var Tau94_AircraftType="Boeing 787-9 Dreamliner";var Tau94_Config = "C28W35Y211"; var Tau94_Day="07/2015"; var Tau94_Age="4.9";
var Tau95_Reg = "VN-A862"; var Tau95_AircraftType="Boeing 787-9 Dreamliner";var Tau95_Config = "C28W35Y211"; var Tau95_Day="08/2015"; var Tau95_Age="4.7";
var Tau96_Reg = "VN-A863"; var Tau96_AircraftType="Boeing 787-9 Dreamliner";var Tau96_Config = "C28W35Y211"; var Tau96_Day="08/2015"; var Tau96_Age="4.7";
var Tau97_Reg = "VN-A864"; var Tau97_AircraftType="Boeing 787-9 Dreamliner";var Tau97_Config = "C28W35Y211"; var Tau97_Day="10/2015"; var Tau97_Age="4.5";
var Tau98_Reg = "VN-A865"; var Tau98_AircraftType="Boeing 787-9 Dreamliner";var Tau98_Config = "C28Y283"; var Tau98_Day="12/2015"; var Tau98_Age="4.4";
var Tau99_Reg = "VN-A866"; var Tau99_AircraftType="Boeing 787-9 Dreamliner";var Tau99_Config = "C28Y283"; var Tau99_Day="01/2016"; var Tau99_Age="4.3";
var Tau100_Reg = "VN-A867"; var Tau100_AircraftType="Boeing 787-9 Dreamliner";var Tau100_Config = "C28W35Y211"; var Tau100_Day="04/2016"; var Tau100_Age="4.1";
var Tau101_Reg = "VN-A868"; var Tau101_AircraftType="Boeing 787-9 Dreamliner";var Tau101_Config = "C28W35Y211"; var Tau101_Day="10/2016"; var Tau101_Age="3.7";
var Tau102_Reg = "VN-A869"; var Tau102_AircraftType="Boeing 787-9 Dreamliner";var Tau102_Config = "C28Y283"; var Tau102_Day="10/2016"; var Tau102_Age="3.6";
var Tau103_Reg = "VN-A870"; var Tau103_AircraftType="Boeing 787-9 Dreamliner";var Tau103_Config = "C28W35Y211"; var Tau103_Day="11/2016"; var Tau103_Age="3.5";
var Tau104_Reg = "VN-A871"; var Tau104_AircraftType="Boeing 787-9 Dreamliner";var Tau104_Config = "C28W35Y211"; var Tau104_Day="05/2017"; var Tau104_Age="3.0";
var Tau105_Reg = "VN-A"; var Tau105_AircraftType="";var Tau105_Config = ""; var Tau105_Day=""; var Tau105_Age="";
var Tau106_Reg = "VN-A"; var Tau106_AircraftType="";var Tau106_Config = ""; var Tau106_Day=""; var Tau106_Age="";
var Tau107_Reg = "VN-A"; var Tau107_AircraftType="";var Tau107_Config = ""; var Tau107_Day=""; var Tau107_Age="";
var Tau108_Reg = "VN-A"; var Tau108_AircraftType="";var Tau108_Config = ""; var Tau108_Day=""; var Tau108_Age="";
var Tau109_Reg = "VN-A"; var Tau109_AircraftType="";var Tau109_Config = ""; var Tau109_Day=""; var Tau109_Age="";
var Tau110_Reg = "VN-A"; var Tau110_AircraftType="";var Tau110_Config = ""; var Tau110_Day=""; var Tau110_Age="";
var Tau111_Reg = "VN-A"; var Tau111_AircraftType="";var Tau111_Config = ""; var Tau111_Day=""; var Tau111_Age="";
var Tau112_Reg = "VN-A"; var Tau112_AircraftType="";var Tau112_Config = ""; var Tau112_Day=""; var Tau112_Age="";
var Tau113_Reg = "VN-A"; var Tau113_AircraftType="";var Tau113_Config = ""; var Tau113_Day=""; var Tau113_Age="";
var Tau114_Reg = "VN-A"; var Tau114_AircraftType="";var Tau114_Config = ""; var Tau114_Day=""; var Tau114_Age="";
var Tau115_Reg = "VN-A"; var Tau115_AircraftType="";var Tau115_Config = ""; var Tau115_Day=""; var Tau115_Age="";


var AHK1_address = "../Picture/IMG_00014.jpg";
var AHK2_address = "../Picture/IMG_00019.jpg";
var AHK3_address = "../Picture/IMG_00025.jpg";
var AHK4_address = "../Picture/IMG_00028.jpg";
var AHK5_address = "../Picture/IMG_00030.jpg";
var AHK6_address = "../Picture/IMG_00032.jpg";
var AHK7_address = "../Picture/IMG_1432.jpg";
var AHK8_address = "../Picture/IMG_2345.jpg";
var AHK9_address = "../Picture/IMG_8804.jpg";
var AHK10_address = "../Picture/IMG_VNA_00001.jpg";
var AHK11_address = "../Picture/IMG_VNA_00002.jpg";
var AHK12_address = "../Picture/IMG_VNA_00003.jpg";
var AHK13_address = "../Picture/IMG_VNA_00004.jpg";
var AHK14_address = "../Picture/IMG_VNA_00005.jpg";
var AHK15_address = "../Picture/IMG_VNA_00006.jpg";
var AHK16_address = "../Picture/IMG_VNA_00007.jpg";
var AHK17_address = "../Picture/IMG_VNA_00008.jpg";
var AHK18_address = "../Picture/IMG_VNA_00009.jpg";
var AHK19_address = "../Picture/IMG_VNA_00010.jpg";
var AHK20_address = "../Picture/IMG_VNA_00011.jpg";
var AHK21_address = "../Picture/IMG_VNA_00012.jpg";
var AHK22_address = "../Picture/IMG_VNA_00013.jpg";
var AHK23_address = "../Picture/IMG_VNA_00014.jpg";
var AHK24_address = "../Picture/IMG_VNA_00015.jpg";


var AHK1Info = "Vietnam Airlines <br> Airbus 350-900 <br> Reg: VN-A890 <br> Tác giả: ";
var AHK2Info = "Vietnam Airlines <br> Boeing 787-9 Dreamliner <br> Reg: VN-A865 <br> Tác giả:  ";
var AHK3Info = "Vietnam Airlines <br> Airbus A321Neo <br> Reg: VN-A508 <br> Tác giả: ";
var AHK4Info = "Vietnam Airlines <br> Boeing 787-9 Dreamliner <br> Reg: VN-A871 <br> Tác giả: ";
var AHK5Info = "Vietnam Airlines <br> Airbus A321Neo <br> Reg: VN-A625 <br> Tác giả: ";
var AHK6Info = "Vietnam Airlines <br> Airbus A321-200 <br> Reg: VN-A332 <br> Tác giả:  ";
var AHK7Info = "Vietnam Airlines <br> Airbus A321-200 <br> Reg: VN-A367 <br> Tác giả:  ";
var AHK8Info = "Vietnam Airlines <br> Boeing 787-9 Dreamliner <br> Reg: VN-A870 <br> Tác giả: ";
var AHK9Info = "Vietnam Airlines <br> Airbus A321Neo <br> Reg: VN-A510 <br> Tác giả: ";
var AHK10Info = "Vietnam Airlines <br> Boeing 787-10 Dreamliner <br> Reg: VN-A873 <br> Tác giả: ";
var AHK11Info = "Vietnam Airlines <br> Airbus A321-200 <br> Reg: VN-A610 <br> Tác giả: ";
var AHK12Info = "Vietnam Airlines <br> Airbus A321Neo <br> Reg: VN-A507 <br> Tác giả: ";
var AHK13Info = "Vietnam Airlines <br> Boeing 787-9 Dreamliner <br> Reg: VN-A862 <br> Tác giả: ";
var AHK14Info = "Vietnam Airlines <br> Boeing 787-9 Dreamliner <br> Reg: VN-A864 <br> Tác giả: ";
var AHK15Info = "Vietnam Airlines <br> Airbus 350-900 <br> Reg: VN-A892 <br> Tác giả: ";
var AHK16Info = "Vietnam Airlines <br> Airbus 350-900 <br> Reg: VN-A895 <br> Tác giả: ";
var AHK17Info = "Vietnam Airlines <br> Boeing 787-9 Dreamliner <br> Reg: VN-A868 <br> Tác giả: ";
var AHK18Info = "Vietnam Airlines <br> Airbus A321-200 <br> Reg: VN-A609 <br> Tác giả: ";
var AHK19Info = "Vietnam Airlines <br> Boeing 787-10 Dreamliner <br> Reg: VN-A879 <br> Tác giả: ";
var AHK20Info = "Vietnam Airlines <br> Boeing 787-9 Dreamliner <br> Reg: VN-A863 <br> Tác giả: ";
var AHK21Info = "Vietnam Airlines <br> Airbus 350-900 <br> Reg: VN-A899 <br> Tác giả: ";
var AHK22Info = "Vietnam Airlines <br> Airbus A321-200 <br> Reg: VN-A327 <br> Tác giả: ";
var AHK23Info = "Vietnam Airlines <br> Boeing 787-10 Dreamliner <br> Reg: VN-A872 <br> Tác giả: ";
var AHK24Info = "Vietnam Airlines <br> Airbus 350-900 <br> Reg: VN-A897 <br> Tác giả: ";

function XULITHONGTINTHEMES()
{
	document.getElementById('WebsiteName').innerHTML=WebsiteName;
	document.getElementById('Slogan').innerHTML=SLOGAN;
	document.getElementById('TieuDeChuyenMuc').innerHTML=TieuDeChuyenMuc;
}

function XULITHONGTINHINHANH()
{
	$('#HotPic1').attr("src",HotPic1_address);
	$('#HotPic2').attr("src",HotPic2_address);
	$('#HotPic3').attr("src",HotPic3_address);
	$('#HotPic4').attr("src",HotPic4_address);
	$('#AdvertisingPic').attr("src",AdvertisingPic);
	$('#Banner_VNA').attr("src",BannerVNA_address);
}

function XULITHONGTINBANG1()
{
	document.getElementById('Tau1_Reg').innerHTML=Tau1_Reg;
	document.getElementById('Tau1_AircraftType').innerHTML=Tau1_AircraftType;
	document.getElementById('Tau1_Config').innerHTML=Tau1_Config;
	document.getElementById('Tau1_Day').innerHTML=Tau1_Day;
	document.getElementById('Tau1_Age').innerHTML=Tau1_Age;
	document.getElementById('Tau2_Reg').innerHTML=Tau2_Reg;
	document.getElementById('Tau2_AircraftType').innerHTML=Tau2_AircraftType;
	document.getElementById('Tau2_Config').innerHTML=Tau2_Config;
	document.getElementById('Tau2_Day').innerHTML=Tau2_Day;
	document.getElementById('Tau2_Age').innerHTML=Tau2_Age;
	document.getElementById('Tau3_Reg').innerHTML=Tau3_Reg;
	document.getElementById('Tau3_AircraftType').innerHTML=Tau3_AircraftType;
	document.getElementById('Tau3_Config').innerHTML=Tau3_Config;
	document.getElementById('Tau3_Day').innerHTML=Tau3_Day;
	document.getElementById('Tau3_Age').innerHTML=Tau3_Age;
	document.getElementById('Tau4_Reg').innerHTML=Tau4_Reg;
	document.getElementById('Tau4_AircraftType').innerHTML=Tau4_AircraftType;
	document.getElementById('Tau4_Config').innerHTML=Tau4_Config;
	document.getElementById('Tau4_Day').innerHTML=Tau4_Day;
	document.getElementById('Tau4_Age').innerHTML=Tau4_Age;
	document.getElementById('Tau5_Reg').innerHTML=Tau5_Reg;
	document.getElementById('Tau5_AircraftType').innerHTML=Tau5_AircraftType;
	document.getElementById('Tau5_Config').innerHTML=Tau5_Config;
	document.getElementById('Tau5_Day').innerHTML=Tau5_Day;
	document.getElementById('Tau5_Age').innerHTML=Tau5_Age;
	document.getElementById('Tau6_Reg').innerHTML=Tau6_Reg;
	document.getElementById('Tau6_AircraftType').innerHTML=Tau6_AircraftType;
	document.getElementById('Tau6_Config').innerHTML=Tau6_Config;
	document.getElementById('Tau6_Day').innerHTML=Tau6_Day;
	document.getElementById('Tau6_Age').innerHTML=Tau6_Age;
	document.getElementById('Tau7_Reg').innerHTML=Tau7_Reg;
	document.getElementById('Tau7_AircraftType').innerHTML=Tau7_AircraftType;
	document.getElementById('Tau7_Config').innerHTML=Tau7_Config;
	document.getElementById('Tau7_Day').innerHTML=Tau7_Day;
	document.getElementById('Tau7_Age').innerHTML=Tau7_Age;
	document.getElementById('Tau8_Reg').innerHTML=Tau8_Reg;
	document.getElementById('Tau8_AircraftType').innerHTML=Tau8_AircraftType;
	document.getElementById('Tau8_Config').innerHTML=Tau8_Config;
	document.getElementById('Tau8_Day').innerHTML=Tau8_Day;
	document.getElementById('Tau8_Age').innerHTML=Tau8_Age;
	document.getElementById('Tau9_Reg').innerHTML=Tau9_Reg;
	document.getElementById('Tau9_AircraftType').innerHTML=Tau9_AircraftType;
	document.getElementById('Tau9_Config').innerHTML=Tau9_Config;
	document.getElementById('Tau9_Day').innerHTML=Tau9_Day;
	document.getElementById('Tau9_Age').innerHTML=Tau9_Age;
	document.getElementById('Tau10_Reg').innerHTML=Tau10_Reg;
	document.getElementById('Tau10_AircraftType').innerHTML=Tau10_AircraftType;
	document.getElementById('Tau10_Config').innerHTML=Tau10_Config;
	document.getElementById('Tau10_Day').innerHTML=Tau10_Day;
	document.getElementById('Tau10_Age').innerHTML=Tau10_Age;
	document.getElementById('Tau11_Reg').innerHTML=Tau11_Reg;
	document.getElementById('Tau11_AircraftType').innerHTML=Tau11_AircraftType;
	document.getElementById('Tau11_Config').innerHTML=Tau11_Config;
	document.getElementById('Tau11_Day').innerHTML=Tau11_Day;
	document.getElementById('Tau11_Age').innerHTML=Tau11_Age;
	document.getElementById('Tau12_Reg').innerHTML=Tau12_Reg;
	document.getElementById('Tau12_AircraftType').innerHTML=Tau12_AircraftType;
	document.getElementById('Tau12_Config').innerHTML=Tau12_Config;
	document.getElementById('Tau12_Day').innerHTML=Tau12_Day;
	document.getElementById('Tau12_Age').innerHTML=Tau12_Age;
	document.getElementById('Tau13_Reg').innerHTML=Tau13_Reg;
	document.getElementById('Tau13_AircraftType').innerHTML=Tau13_AircraftType;
	document.getElementById('Tau13_Config').innerHTML=Tau13_Config;
	document.getElementById('Tau13_Day').innerHTML=Tau13_Day;
	document.getElementById('Tau13_Age').innerHTML=Tau13_Age;
	document.getElementById('Tau14_Reg').innerHTML=Tau14_Reg;
	document.getElementById('Tau14_AircraftType').innerHTML=Tau14_AircraftType;
	document.getElementById('Tau14_Config').innerHTML=Tau14_Config;
	document.getElementById('Tau14_Day').innerHTML=Tau14_Day;
	document.getElementById('Tau14_Age').innerHTML=Tau14_Age;
	document.getElementById('Tau15_Reg').innerHTML=Tau15_Reg;
	document.getElementById('Tau15_AircraftType').innerHTML=Tau15_AircraftType;
	document.getElementById('Tau15_Config').innerHTML=Tau15_Config;
	document.getElementById('Tau15_Day').innerHTML=Tau15_Day;
	document.getElementById('Tau15_Age').innerHTML=Tau15_Age;
	document.getElementById('Tau16_Reg').innerHTML=Tau16_Reg;
	document.getElementById('Tau16_AircraftType').innerHTML=Tau16_AircraftType;
	document.getElementById('Tau16_Config').innerHTML=Tau16_Config;
	document.getElementById('Tau16_Day').innerHTML=Tau16_Day;
	document.getElementById('Tau16_Age').innerHTML=Tau16_Age;
	document.getElementById('Tau17_Reg').innerHTML=Tau17_Reg;
	document.getElementById('Tau17_AircraftType').innerHTML=Tau17_AircraftType;
	document.getElementById('Tau17_Config').innerHTML=Tau17_Config;
	document.getElementById('Tau17_Day').innerHTML=Tau17_Day;
	document.getElementById('Tau17_Age').innerHTML=Tau17_Age;
	document.getElementById('Tau18_Reg').innerHTML=Tau18_Reg;
	document.getElementById('Tau18_AircraftType').innerHTML=Tau18_AircraftType;
	document.getElementById('Tau18_Config').innerHTML=Tau18_Config;
	document.getElementById('Tau18_Day').innerHTML=Tau18_Day;
	document.getElementById('Tau18_Age').innerHTML=Tau18_Age;
	document.getElementById('Tau19_Reg').innerHTML=Tau19_Reg;
	document.getElementById('Tau19_AircraftType').innerHTML=Tau19_AircraftType;
	document.getElementById('Tau19_Config').innerHTML=Tau19_Config;
	document.getElementById('Tau19_Day').innerHTML=Tau19_Day;
	document.getElementById('Tau19_Age').innerHTML=Tau19_Age;
	document.getElementById('Tau20_Reg').innerHTML=Tau20_Reg;
	document.getElementById('Tau20_AircraftType').innerHTML=Tau20_AircraftType;
	document.getElementById('Tau20_Config').innerHTML=Tau20_Config;
	document.getElementById('Tau20_Day').innerHTML=Tau20_Day;
	document.getElementById('Tau20_Age').innerHTML=Tau20_Age;
	document.getElementById('Tau21_Reg').innerHTML=Tau21_Reg;
	document.getElementById('Tau21_AircraftType').innerHTML=Tau21_AircraftType;
	document.getElementById('Tau21_Config').innerHTML=Tau21_Config;
	document.getElementById('Tau21_Day').innerHTML=Tau21_Day;
	document.getElementById('Tau21_Age').innerHTML=Tau21_Age;
	document.getElementById('Tau22_Reg').innerHTML=Tau22_Reg;
	document.getElementById('Tau22_AircraftType').innerHTML=Tau22_AircraftType;
	document.getElementById('Tau22_Config').innerHTML=Tau22_Config;
	document.getElementById('Tau22_Day').innerHTML=Tau22_Day;
	document.getElementById('Tau22_Age').innerHTML=Tau22_Age;
	document.getElementById('Tau23_Reg').innerHTML=Tau23_Reg;
	document.getElementById('Tau23_AircraftType').innerHTML=Tau23_AircraftType;
	document.getElementById('Tau23_Config').innerHTML=Tau23_Config;
	document.getElementById('Tau23_Day').innerHTML=Tau23_Day;
	document.getElementById('Tau23_Age').innerHTML=Tau23_Age;
	document.getElementById('Button1T').style.backgroundColor='white';
	document.getElementById('Button1T').style.color='black';
	document.getElementById('Button2T').style.backgroundColor='black';
	document.getElementById('Button2T').style.color='white';
	document.getElementById('Button3T').style.backgroundColor='black';
	document.getElementById('Button3T').style.color='white';
	document.getElementById('Button4T').style.backgroundColor='black';
	document.getElementById('Button4T').style.color='white';
	document.getElementById('Button5T').style.backgroundColor='black';
	document.getElementById('Button5T').style.color='white';
}

function XULITHONGTINBANG2()
{
	document.getElementById('Tau1_Reg').innerHTML=Tau24_Reg;
	document.getElementById('Tau1_AircraftType').innerHTML=Tau24_AircraftType;
	document.getElementById('Tau1_Config').innerHTML=Tau24_Config;
	document.getElementById('Tau1_Day').innerHTML=Tau24_Day;
	document.getElementById('Tau1_Age').innerHTML=Tau24_Age;
	document.getElementById('Tau2_Reg').innerHTML=Tau25_Reg;
	document.getElementById('Tau2_AircraftType').innerHTML=Tau25_AircraftType;
	document.getElementById('Tau2_Config').innerHTML=Tau25_Config;
	document.getElementById('Tau2_Day').innerHTML=Tau25_Day;
	document.getElementById('Tau2_Age').innerHTML=Tau25_Age;
	document.getElementById('Tau3_Reg').innerHTML=Tau26_Reg;
	document.getElementById('Tau3_AircraftType').innerHTML=Tau26_AircraftType;
	document.getElementById('Tau3_Config').innerHTML=Tau26_Config;
	document.getElementById('Tau3_Day').innerHTML=Tau26_Day;
	document.getElementById('Tau3_Age').innerHTML=Tau26_Age;
	document.getElementById('Tau4_Reg').innerHTML=Tau27_Reg;
	document.getElementById('Tau4_AircraftType').innerHTML=Tau27_AircraftType;
	document.getElementById('Tau4_Config').innerHTML=Tau27_Config;
	document.getElementById('Tau4_Day').innerHTML=Tau27_Day;
	document.getElementById('Tau4_Age').innerHTML=Tau27_Age;
	document.getElementById('Tau5_Reg').innerHTML=Tau28_Reg;
	document.getElementById('Tau5_AircraftType').innerHTML=Tau28_AircraftType;
	document.getElementById('Tau5_Config').innerHTML=Tau28_Config;
	document.getElementById('Tau5_Day').innerHTML=Tau28_Day;
	document.getElementById('Tau5_Age').innerHTML=Tau28_Age;
	document.getElementById('Tau6_Reg').innerHTML=Tau29_Reg;
	document.getElementById('Tau6_AircraftType').innerHTML=Tau29_AircraftType;
	document.getElementById('Tau6_Config').innerHTML=Tau29_Config;
	document.getElementById('Tau6_Day').innerHTML=Tau29_Day;
	document.getElementById('Tau6_Age').innerHTML=Tau29_Age;
	document.getElementById('Tau7_Reg').innerHTML=Tau30_Reg;
	document.getElementById('Tau7_AircraftType').innerHTML=Tau30_AircraftType;
	document.getElementById('Tau7_Config').innerHTML=Tau30_Config;
	document.getElementById('Tau7_Day').innerHTML=Tau30_Day;
	document.getElementById('Tau7_Age').innerHTML=Tau30_Age;
	document.getElementById('Tau8_Reg').innerHTML=Tau31_Reg;
	document.getElementById('Tau8_AircraftType').innerHTML=Tau31_AircraftType;
	document.getElementById('Tau8_Config').innerHTML=Tau31_Config;
	document.getElementById('Tau8_Day').innerHTML=Tau31_Day;
	document.getElementById('Tau8_Age').innerHTML=Tau31_Age;
	document.getElementById('Tau9_Reg').innerHTML=Tau32_Reg;
	document.getElementById('Tau9_AircraftType').innerHTML=Tau32_AircraftType;
	document.getElementById('Tau9_Config').innerHTML=Tau32_Config;
	document.getElementById('Tau9_Day').innerHTML=Tau32_Day;
	document.getElementById('Tau9_Age').innerHTML=Tau32_Age;
	document.getElementById('Tau10_Reg').innerHTML=Tau33_Reg;
	document.getElementById('Tau10_AircraftType').innerHTML=Tau33_AircraftType;
	document.getElementById('Tau10_Config').innerHTML=Tau33_Config;
	document.getElementById('Tau10_Day').innerHTML=Tau33_Day;
	document.getElementById('Tau10_Age').innerHTML=Tau33_Age;
	document.getElementById('Tau11_Reg').innerHTML=Tau34_Reg;
	document.getElementById('Tau11_AircraftType').innerHTML=Tau34_AircraftType;
	document.getElementById('Tau11_Config').innerHTML=Tau34_Config;
	document.getElementById('Tau11_Day').innerHTML=Tau34_Day;
	document.getElementById('Tau11_Age').innerHTML=Tau34_Age;
	document.getElementById('Tau12_Reg').innerHTML=Tau35_Reg;
	document.getElementById('Tau12_AircraftType').innerHTML=Tau35_AircraftType;
	document.getElementById('Tau12_Config').innerHTML=Tau35_Config;
	document.getElementById('Tau12_Day').innerHTML=Tau35_Day;
	document.getElementById('Tau12_Age').innerHTML=Tau35_Age;
	document.getElementById('Tau13_Reg').innerHTML=Tau36_Reg;
	document.getElementById('Tau13_AircraftType').innerHTML=Tau36_AircraftType;
	document.getElementById('Tau13_Config').innerHTML=Tau36_Config;
	document.getElementById('Tau13_Day').innerHTML=Tau36_Day;
	document.getElementById('Tau13_Age').innerHTML=Tau36_Age;
	document.getElementById('Tau14_Reg').innerHTML=Tau37_Reg;
	document.getElementById('Tau14_AircraftType').innerHTML=Tau37_AircraftType;
	document.getElementById('Tau14_Config').innerHTML=Tau37_Config;
	document.getElementById('Tau14_Day').innerHTML=Tau37_Day;
	document.getElementById('Tau14_Age').innerHTML=Tau37_Age;
	document.getElementById('Tau15_Reg').innerHTML=Tau38_Reg;
	document.getElementById('Tau15_AircraftType').innerHTML=Tau38_AircraftType;
	document.getElementById('Tau15_Config').innerHTML=Tau38_Config;
	document.getElementById('Tau15_Day').innerHTML=Tau38_Day;
	document.getElementById('Tau15_Age').innerHTML=Tau38_Age;
	document.getElementById('Tau16_Reg').innerHTML=Tau39_Reg;
	document.getElementById('Tau16_AircraftType').innerHTML=Tau39_AircraftType;
	document.getElementById('Tau16_Config').innerHTML=Tau39_Config;
	document.getElementById('Tau16_Day').innerHTML=Tau39_Day;
	document.getElementById('Tau16_Age').innerHTML=Tau39_Age;
	document.getElementById('Tau17_Reg').innerHTML=Tau40_Reg;
	document.getElementById('Tau17_AircraftType').innerHTML=Tau40_AircraftType;
	document.getElementById('Tau17_Config').innerHTML=Tau40_Config;
	document.getElementById('Tau17_Day').innerHTML=Tau40_Day;
	document.getElementById('Tau17_Age').innerHTML=Tau40_Age;
	document.getElementById('Tau18_Reg').innerHTML=Tau41_Reg;
	document.getElementById('Tau18_AircraftType').innerHTML=Tau41_AircraftType;
	document.getElementById('Tau18_Config').innerHTML=Tau41_Config;
	document.getElementById('Tau18_Day').innerHTML=Tau41_Day;
	document.getElementById('Tau18_Age').innerHTML=Tau41_Age;
	document.getElementById('Tau19_Reg').innerHTML=Tau42_Reg;
	document.getElementById('Tau19_AircraftType').innerHTML=Tau42_AircraftType;
	document.getElementById('Tau19_Config').innerHTML=Tau42_Config;
	document.getElementById('Tau19_Day').innerHTML=Tau42_Day;
	document.getElementById('Tau19_Age').innerHTML=Tau42_Age;
	document.getElementById('Tau20_Reg').innerHTML=Tau43_Reg;
	document.getElementById('Tau20_AircraftType').innerHTML=Tau43_AircraftType;
	document.getElementById('Tau20_Config').innerHTML=Tau43_Config;
	document.getElementById('Tau20_Day').innerHTML=Tau43_Day;
	document.getElementById('Tau20_Age').innerHTML=Tau43_Age;
	document.getElementById('Tau21_Reg').innerHTML=Tau44_Reg;
	document.getElementById('Tau21_AircraftType').innerHTML=Tau44_AircraftType;
	document.getElementById('Tau21_Config').innerHTML=Tau44_Config;
	document.getElementById('Tau21_Day').innerHTML=Tau44_Day;
	document.getElementById('Tau21_Age').innerHTML=Tau44_Age;
	document.getElementById('Tau22_Reg').innerHTML=Tau45_Reg;
	document.getElementById('Tau22_AircraftType').innerHTML=Tau45_AircraftType;
	document.getElementById('Tau22_Config').innerHTML=Tau45_Config;
	document.getElementById('Tau22_Day').innerHTML=Tau45_Day;
	document.getElementById('Tau22_Age').innerHTML=Tau45_Age;
	document.getElementById('Tau23_Reg').innerHTML=Tau46_Reg;
	document.getElementById('Tau23_AircraftType').innerHTML=Tau46_AircraftType;
	document.getElementById('Tau23_Config').innerHTML=Tau46_Config;
	document.getElementById('Tau23_Day').innerHTML=Tau46_Day;
	document.getElementById('Tau23_Age').innerHTML=Tau46_Age;
	document.getElementById('Button1T').style.backgroundColor='black';
	document.getElementById('Button1T').style.color='white';
	document.getElementById('Button2T').style.backgroundColor='white';
	document.getElementById('Button2T').style.color='black';
	document.getElementById('Button3T').style.backgroundColor='black';
	document.getElementById('Button3T').style.color='white';
	document.getElementById('Button4T').style.backgroundColor='black';
	document.getElementById('Button4T').style.color='white';
	document.getElementById('Button5T').style.backgroundColor='black';
	document.getElementById('Button5T').style.color='white';
}

function XULITHONGTINBANG3()
{
	document.getElementById('Tau1_Reg').innerHTML=Tau47_Reg;
	document.getElementById('Tau1_AircraftType').innerHTML=Tau47_AircraftType;
	document.getElementById('Tau1_Config').innerHTML=Tau47_Config;
	document.getElementById('Tau1_Day').innerHTML=Tau47_Day;
	document.getElementById('Tau1_Age').innerHTML=Tau47_Age;
	document.getElementById('Tau2_Reg').innerHTML=Tau48_Reg;
	document.getElementById('Tau2_AircraftType').innerHTML=Tau48_AircraftType;
	document.getElementById('Tau2_Config').innerHTML=Tau48_Config;
	document.getElementById('Tau2_Day').innerHTML=Tau48_Day;
	document.getElementById('Tau2_Age').innerHTML=Tau48_Age;
	document.getElementById('Tau3_Reg').innerHTML=Tau49_Reg;
	document.getElementById('Tau3_AircraftType').innerHTML=Tau49_AircraftType;
	document.getElementById('Tau3_Config').innerHTML=Tau49_Config;
	document.getElementById('Tau3_Day').innerHTML=Tau49_Day;
	document.getElementById('Tau3_Age').innerHTML=Tau49_Age;
	document.getElementById('Tau4_Reg').innerHTML=Tau50_Reg;
	document.getElementById('Tau4_AircraftType').innerHTML=Tau50_AircraftType;
	document.getElementById('Tau4_Config').innerHTML=Tau50_Config;
	document.getElementById('Tau4_Day').innerHTML=Tau50_Day;
	document.getElementById('Tau4_Age').innerHTML=Tau50_Age;
	document.getElementById('Tau5_Reg').innerHTML=Tau51_Reg;
	document.getElementById('Tau5_AircraftType').innerHTML=Tau51_AircraftType;
	document.getElementById('Tau5_Config').innerHTML=Tau51_Config;
	document.getElementById('Tau5_Day').innerHTML=Tau51_Day;
	document.getElementById('Tau5_Age').innerHTML=Tau51_Age;
	document.getElementById('Tau6_Reg').innerHTML=Tau52_Reg;
	document.getElementById('Tau6_AircraftType').innerHTML=Tau52_AircraftType;
	document.getElementById('Tau6_Config').innerHTML=Tau52_Config;
	document.getElementById('Tau6_Day').innerHTML=Tau52_Day;
	document.getElementById('Tau6_Age').innerHTML=Tau52_Age;
	document.getElementById('Tau7_Reg').innerHTML=Tau53_Reg;
	document.getElementById('Tau7_AircraftType').innerHTML=Tau53_AircraftType;
	document.getElementById('Tau7_Config').innerHTML=Tau53_Config;
	document.getElementById('Tau7_Day').innerHTML=Tau53_Day;
	document.getElementById('Tau7_Age').innerHTML=Tau53_Age;
	document.getElementById('Tau8_Reg').innerHTML=Tau54_Reg;
	document.getElementById('Tau8_AircraftType').innerHTML=Tau54_AircraftType;
	document.getElementById('Tau8_Config').innerHTML=Tau54_Config;
	document.getElementById('Tau8_Day').innerHTML=Tau54_Day;
	document.getElementById('Tau8_Age').innerHTML=Tau54_Age;
	document.getElementById('Tau9_Reg').innerHTML=Tau55_Reg;
	document.getElementById('Tau9_AircraftType').innerHTML=Tau55_AircraftType;
	document.getElementById('Tau9_Config').innerHTML=Tau55_Config;
	document.getElementById('Tau9_Day').innerHTML=Tau55_Day;
	document.getElementById('Tau9_Age').innerHTML=Tau55_Age;
	document.getElementById('Tau10_Reg').innerHTML=Tau56_Reg;
	document.getElementById('Tau10_AircraftType').innerHTML=Tau56_AircraftType;
	document.getElementById('Tau10_Config').innerHTML=Tau56_Config;
	document.getElementById('Tau10_Day').innerHTML=Tau56_Day;
	document.getElementById('Tau10_Age').innerHTML=Tau56_Age;
	document.getElementById('Tau11_Reg').innerHTML=Tau57_Reg;
	document.getElementById('Tau11_AircraftType').innerHTML=Tau57_AircraftType;
	document.getElementById('Tau11_Config').innerHTML=Tau57_Config;
	document.getElementById('Tau11_Day').innerHTML=Tau57_Day;
	document.getElementById('Tau11_Age').innerHTML=Tau57_Age;
	document.getElementById('Tau12_Reg').innerHTML=Tau58_Reg;
	document.getElementById('Tau12_AircraftType').innerHTML=Tau58_AircraftType;
	document.getElementById('Tau12_Config').innerHTML=Tau58_Config;
	document.getElementById('Tau12_Day').innerHTML=Tau58_Day;
	document.getElementById('Tau12_Age').innerHTML=Tau58_Age;
	document.getElementById('Tau13_Reg').innerHTML=Tau59_Reg;
	document.getElementById('Tau13_AircraftType').innerHTML=Tau59_AircraftType;
	document.getElementById('Tau13_Config').innerHTML=Tau59_Config;
	document.getElementById('Tau13_Day').innerHTML=Tau59_Day;
	document.getElementById('Tau13_Age').innerHTML=Tau59_Age;
	document.getElementById('Tau14_Reg').innerHTML=Tau60_Reg;
	document.getElementById('Tau14_AircraftType').innerHTML=Tau60_AircraftType;
	document.getElementById('Tau14_Config').innerHTML=Tau60_Config;
	document.getElementById('Tau14_Day').innerHTML=Tau60_Day;
	document.getElementById('Tau14_Age').innerHTML=Tau60_Age;
	document.getElementById('Tau15_Reg').innerHTML=Tau61_Reg;
	document.getElementById('Tau15_AircraftType').innerHTML=Tau61_AircraftType;
	document.getElementById('Tau15_Config').innerHTML=Tau61_Config;
	document.getElementById('Tau15_Day').innerHTML=Tau61_Day;
	document.getElementById('Tau15_Age').innerHTML=Tau61_Age;
	document.getElementById('Tau16_Reg').innerHTML=Tau62_Reg;
	document.getElementById('Tau16_AircraftType').innerHTML=Tau62_AircraftType;
	document.getElementById('Tau16_Config').innerHTML=Tau62_Config;
	document.getElementById('Tau16_Day').innerHTML=Tau62_Day;
	document.getElementById('Tau16_Age').innerHTML=Tau62_Age;
	document.getElementById('Tau17_Reg').innerHTML=Tau63_Reg;
	document.getElementById('Tau17_AircraftType').innerHTML=Tau63_AircraftType;
	document.getElementById('Tau17_Config').innerHTML=Tau63_Config;
	document.getElementById('Tau17_Day').innerHTML=Tau63_Day;
	document.getElementById('Tau17_Age').innerHTML=Tau63_Age;
	document.getElementById('Tau18_Reg').innerHTML=Tau64_Reg;
	document.getElementById('Tau18_AircraftType').innerHTML=Tau64_AircraftType;
	document.getElementById('Tau18_Config').innerHTML=Tau64_Config;
	document.getElementById('Tau18_Day').innerHTML=Tau64_Day;
	document.getElementById('Tau18_Age').innerHTML=Tau64_Age;
	document.getElementById('Tau19_Reg').innerHTML=Tau65_Reg;
	document.getElementById('Tau19_AircraftType').innerHTML=Tau65_AircraftType;
	document.getElementById('Tau19_Config').innerHTML=Tau65_Config;
	document.getElementById('Tau19_Day').innerHTML=Tau65_Day;
	document.getElementById('Tau19_Age').innerHTML=Tau65_Age;
	document.getElementById('Tau20_Reg').innerHTML=Tau66_Reg;
	document.getElementById('Tau20_AircraftType').innerHTML=Tau66_AircraftType;
	document.getElementById('Tau20_Config').innerHTML=Tau66_Config;
	document.getElementById('Tau20_Day').innerHTML=Tau66_Day;
	document.getElementById('Tau20_Age').innerHTML=Tau66_Age;
	document.getElementById('Tau21_Reg').innerHTML=Tau67_Reg;
	document.getElementById('Tau21_AircraftType').innerHTML=Tau67_AircraftType;
	document.getElementById('Tau21_Config').innerHTML=Tau67_Config;
	document.getElementById('Tau21_Day').innerHTML=Tau67_Day;
	document.getElementById('Tau21_Age').innerHTML=Tau67_Age;
	document.getElementById('Tau22_Reg').innerHTML=Tau68_Reg;
	document.getElementById('Tau22_AircraftType').innerHTML=Tau68_AircraftType;
	document.getElementById('Tau22_Config').innerHTML=Tau68_Config;
	document.getElementById('Tau22_Day').innerHTML=Tau68_Day;
	document.getElementById('Tau22_Age').innerHTML=Tau68_Age;
	document.getElementById('Tau23_Reg').innerHTML=Tau69_Reg;
	document.getElementById('Tau23_AircraftType').innerHTML=Tau69_AircraftType;
	document.getElementById('Tau23_Config').innerHTML=Tau69_Config;
	document.getElementById('Tau23_Day').innerHTML=Tau69_Day;
	document.getElementById('Tau23_Age').innerHTML=Tau69_Age;
	document.getElementById('Button1T').style.backgroundColor='black';
	document.getElementById('Button1T').style.color='white';
	document.getElementById('Button2T').style.backgroundColor='black';
	document.getElementById('Button2T').style.color='white';
	document.getElementById('Button3T').style.backgroundColor='white';
	document.getElementById('Button3T').style.color='black';
	document.getElementById('Button4T').style.backgroundColor='black';
	document.getElementById('Button4T').style.color='white';
	document.getElementById('Button5T').style.backgroundColor='black';
	document.getElementById('Button5T').style.color='white';
}

function XULITHONGTINBANG4()
{
	document.getElementById('Tau1_Reg').innerHTML=Tau70_Reg;
	document.getElementById('Tau1_AircraftType').innerHTML=Tau70_AircraftType;
	document.getElementById('Tau1_Config').innerHTML=Tau70_Config;
	document.getElementById('Tau1_Day').innerHTML=Tau70_Day;
	document.getElementById('Tau1_Age').innerHTML=Tau70_Age;
	document.getElementById('Tau2_Reg').innerHTML=Tau71_Reg;
	document.getElementById('Tau2_AircraftType').innerHTML=Tau71_AircraftType;
	document.getElementById('Tau2_Config').innerHTML=Tau71_Config;
	document.getElementById('Tau2_Day').innerHTML=Tau71_Day;
	document.getElementById('Tau2_Age').innerHTML=Tau71_Age;
	document.getElementById('Tau3_Reg').innerHTML=Tau72_Reg;
	document.getElementById('Tau3_AircraftType').innerHTML=Tau72_AircraftType;
	document.getElementById('Tau3_Config').innerHTML=Tau72_Config;
	document.getElementById('Tau3_Day').innerHTML=Tau72_Day;
	document.getElementById('Tau3_Age').innerHTML=Tau72_Age;
	document.getElementById('Tau4_Reg').innerHTML=Tau73_Reg;
	document.getElementById('Tau4_AircraftType').innerHTML=Tau73_AircraftType;
	document.getElementById('Tau4_Config').innerHTML=Tau73_Config;
	document.getElementById('Tau4_Day').innerHTML=Tau73_Day;
	document.getElementById('Tau4_Age').innerHTML=Tau73_Age;
	document.getElementById('Tau5_Reg').innerHTML=Tau74_Reg;
	document.getElementById('Tau5_AircraftType').innerHTML=Tau74_AircraftType;
	document.getElementById('Tau5_Config').innerHTML=Tau74_Config;
	document.getElementById('Tau5_Day').innerHTML=Tau74_Day;
	document.getElementById('Tau5_Age').innerHTML=Tau74_Age;
	document.getElementById('Tau6_Reg').innerHTML=Tau75_Reg;
	document.getElementById('Tau6_AircraftType').innerHTML=Tau75_AircraftType;
	document.getElementById('Tau6_Config').innerHTML=Tau75_Config;
	document.getElementById('Tau6_Day').innerHTML=Tau75_Day;
	document.getElementById('Tau6_Age').innerHTML=Tau75_Age;
	document.getElementById('Tau7_Reg').innerHTML=Tau76_Reg;
	document.getElementById('Tau7_AircraftType').innerHTML=Tau76_AircraftType;
	document.getElementById('Tau7_Config').innerHTML=Tau76_Config;
	document.getElementById('Tau7_Day').innerHTML=Tau76_Day;
	document.getElementById('Tau7_Age').innerHTML=Tau76_Age;
	document.getElementById('Tau8_Reg').innerHTML=Tau77_Reg;
	document.getElementById('Tau8_AircraftType').innerHTML=Tau77_AircraftType;
	document.getElementById('Tau8_Config').innerHTML=Tau77_Config;
	document.getElementById('Tau8_Day').innerHTML=Tau77_Day;
	document.getElementById('Tau8_Age').innerHTML=Tau77_Age;
	document.getElementById('Tau9_Reg').innerHTML=Tau78_Reg;
	document.getElementById('Tau9_AircraftType').innerHTML=Tau78_AircraftType;
	document.getElementById('Tau9_Config').innerHTML=Tau78_Config;
	document.getElementById('Tau9_Day').innerHTML=Tau78_Day;
	document.getElementById('Tau9_Age').innerHTML=Tau78_Age;
	document.getElementById('Tau10_Reg').innerHTML=Tau79_Reg;
	document.getElementById('Tau10_AircraftType').innerHTML=Tau79_AircraftType;
	document.getElementById('Tau10_Config').innerHTML=Tau79_Config;
	document.getElementById('Tau10_Day').innerHTML=Tau79_Day;
	document.getElementById('Tau10_Age').innerHTML=Tau79_Age;
	document.getElementById('Tau11_Reg').innerHTML=Tau80_Reg;
	document.getElementById('Tau11_AircraftType').innerHTML=Tau80_AircraftType;
	document.getElementById('Tau11_Config').innerHTML=Tau80_Config;
	document.getElementById('Tau11_Day').innerHTML=Tau80_Day;
	document.getElementById('Tau11_Age').innerHTML=Tau80_Age;
	document.getElementById('Tau12_Reg').innerHTML=Tau81_Reg;
	document.getElementById('Tau12_AircraftType').innerHTML=Tau81_AircraftType;
	document.getElementById('Tau12_Config').innerHTML=Tau81_Config;
	document.getElementById('Tau12_Day').innerHTML=Tau81_Day;
	document.getElementById('Tau12_Age').innerHTML=Tau81_Age;
	document.getElementById('Tau13_Reg').innerHTML=Tau82_Reg;
	document.getElementById('Tau13_AircraftType').innerHTML=Tau82_AircraftType;
	document.getElementById('Tau13_Config').innerHTML=Tau82_Config;
	document.getElementById('Tau13_Day').innerHTML=Tau82_Day;
	document.getElementById('Tau13_Age').innerHTML=Tau82_Age;
	document.getElementById('Tau14_Reg').innerHTML=Tau83_Reg;
	document.getElementById('Tau14_AircraftType').innerHTML=Tau83_AircraftType;
	document.getElementById('Tau14_Config').innerHTML=Tau83_Config;
	document.getElementById('Tau14_Day').innerHTML=Tau83_Day;
	document.getElementById('Tau14_Age').innerHTML=Tau83_Age;
	document.getElementById('Tau15_Reg').innerHTML=Tau84_Reg;
	document.getElementById('Tau15_AircraftType').innerHTML=Tau84_AircraftType;
	document.getElementById('Tau15_Config').innerHTML=Tau84_Config;
	document.getElementById('Tau15_Day').innerHTML=Tau84_Day;
	document.getElementById('Tau15_Age').innerHTML=Tau84_Age;
	document.getElementById('Tau16_Reg').innerHTML=Tau85_Reg;
	document.getElementById('Tau16_AircraftType').innerHTML=Tau85_AircraftType;
	document.getElementById('Tau16_Config').innerHTML=Tau85_Config;
	document.getElementById('Tau16_Day').innerHTML=Tau85_Day;
	document.getElementById('Tau16_Age').innerHTML=Tau85_Age;
	document.getElementById('Tau17_Reg').innerHTML=Tau86_Reg;
	document.getElementById('Tau17_AircraftType').innerHTML=Tau86_AircraftType;
	document.getElementById('Tau17_Config').innerHTML=Tau86_Config;
	document.getElementById('Tau17_Day').innerHTML=Tau86_Day;
	document.getElementById('Tau17_Age').innerHTML=Tau86_Age;
	document.getElementById('Tau18_Reg').innerHTML=Tau87_Reg;
	document.getElementById('Tau18_AircraftType').innerHTML=Tau87_AircraftType;
	document.getElementById('Tau18_Config').innerHTML=Tau87_Config;
	document.getElementById('Tau18_Day').innerHTML=Tau87_Day;
	document.getElementById('Tau18_Age').innerHTML=Tau87_Age;
	document.getElementById('Tau19_Reg').innerHTML=Tau88_Reg;
	document.getElementById('Tau19_AircraftType').innerHTML=Tau88_AircraftType;
	document.getElementById('Tau19_Config').innerHTML=Tau88_Config;
	document.getElementById('Tau19_Day').innerHTML=Tau88_Day;
	document.getElementById('Tau19_Age').innerHTML=Tau88_Age;
	document.getElementById('Tau20_Reg').innerHTML=Tau89_Reg;
	document.getElementById('Tau20_AircraftType').innerHTML=Tau89_AircraftType;
	document.getElementById('Tau20_Config').innerHTML=Tau89_Config;
	document.getElementById('Tau20_Day').innerHTML=Tau89_Day;
	document.getElementById('Tau20_Age').innerHTML=Tau89_Age;
	document.getElementById('Tau21_Reg').innerHTML=Tau90_Reg;
	document.getElementById('Tau21_AircraftType').innerHTML=Tau90_AircraftType;
	document.getElementById('Tau21_Config').innerHTML=Tau90_Config;
	document.getElementById('Tau21_Day').innerHTML=Tau90_Day;
	document.getElementById('Tau21_Age').innerHTML=Tau90_Age;
	document.getElementById('Tau22_Reg').innerHTML=Tau91_Reg;
	document.getElementById('Tau22_AircraftType').innerHTML=Tau91_AircraftType;
	document.getElementById('Tau22_Config').innerHTML=Tau91_Config;
	document.getElementById('Tau22_Day').innerHTML=Tau91_Day;
	document.getElementById('Tau22_Age').innerHTML=Tau91_Age;
	document.getElementById('Tau23_Reg').innerHTML=Tau92_Reg;
	document.getElementById('Tau23_AircraftType').innerHTML=Tau92_AircraftType;
	document.getElementById('Tau23_Config').innerHTML=Tau92_Config;
	document.getElementById('Tau23_Day').innerHTML=Tau92_Day;
	document.getElementById('Tau23_Age').innerHTML=Tau92_Age;
	document.getElementById('Button1T').style.backgroundColor='black';
	document.getElementById('Button1T').style.color='white';
	document.getElementById('Button2T').style.backgroundColor='black';
	document.getElementById('Button2T').style.color='white';
	document.getElementById('Button3T').style.backgroundColor='black';
	document.getElementById('Button3T').style.color='white';
	document.getElementById('Button4T').style.backgroundColor='white';
	document.getElementById('Button4T').style.color='black';
	document.getElementById('Button5T').style.backgroundColor='black';
	document.getElementById('Button5T').style.color='white';
}

function XULITHONGTINBANG5()
{
	document.getElementById('Tau1_Reg').innerHTML=Tau93_Reg;
	document.getElementById('Tau1_AircraftType').innerHTML=Tau93_AircraftType;
	document.getElementById('Tau1_Config').innerHTML=Tau93_Config;
	document.getElementById('Tau1_Day').innerHTML=Tau93_Day;
	document.getElementById('Tau1_Age').innerHTML=Tau93_Age;
	document.getElementById('Tau2_Reg').innerHTML=Tau94_Reg;
	document.getElementById('Tau2_AircraftType').innerHTML=Tau94_AircraftType;
	document.getElementById('Tau2_Config').innerHTML=Tau94_Config;
	document.getElementById('Tau2_Day').innerHTML=Tau94_Day;
	document.getElementById('Tau2_Age').innerHTML=Tau94_Age;
	document.getElementById('Tau3_Reg').innerHTML=Tau95_Reg;
	document.getElementById('Tau3_AircraftType').innerHTML=Tau95_AircraftType;
	document.getElementById('Tau3_Config').innerHTML=Tau95_Config;
	document.getElementById('Tau3_Day').innerHTML=Tau95_Day;
	document.getElementById('Tau3_Age').innerHTML=Tau95_Age;
	document.getElementById('Tau4_Reg').innerHTML=Tau96_Reg;
	document.getElementById('Tau4_AircraftType').innerHTML=Tau96_AircraftType;
	document.getElementById('Tau4_Config').innerHTML=Tau96_Config;
	document.getElementById('Tau4_Day').innerHTML=Tau96_Day;
	document.getElementById('Tau4_Age').innerHTML=Tau96_Age;
	document.getElementById('Tau5_Reg').innerHTML=Tau97_Reg;
	document.getElementById('Tau5_AircraftType').innerHTML=Tau97_AircraftType;
	document.getElementById('Tau5_Config').innerHTML=Tau97_Config;
	document.getElementById('Tau5_Day').innerHTML=Tau97_Day;
	document.getElementById('Tau5_Age').innerHTML=Tau97_Age;
	document.getElementById('Tau6_Reg').innerHTML=Tau98_Reg;
	document.getElementById('Tau6_AircraftType').innerHTML=Tau98_AircraftType;
	document.getElementById('Tau6_Config').innerHTML=Tau98_Config;
	document.getElementById('Tau6_Day').innerHTML=Tau98_Day;
	document.getElementById('Tau6_Age').innerHTML=Tau98_Age;
	document.getElementById('Tau7_Reg').innerHTML=Tau99_Reg;
	document.getElementById('Tau7_AircraftType').innerHTML=Tau99_AircraftType;
	document.getElementById('Tau7_Config').innerHTML=Tau99_Config;
	document.getElementById('Tau7_Day').innerHTML=Tau99_Day;
	document.getElementById('Tau7_Age').innerHTML=Tau99_Age;
	document.getElementById('Tau8_Reg').innerHTML=Tau100_Reg;
	document.getElementById('Tau8_AircraftType').innerHTML=Tau100_AircraftType;
	document.getElementById('Tau8_Config').innerHTML=Tau100_Config;
	document.getElementById('Tau8_Day').innerHTML=Tau100_Day;
	document.getElementById('Tau8_Age').innerHTML=Tau100_Age;
	document.getElementById('Tau9_Reg').innerHTML=Tau101_Reg;
	document.getElementById('Tau9_AircraftType').innerHTML=Tau101_AircraftType;
	document.getElementById('Tau9_Config').innerHTML=Tau101_Config;
	document.getElementById('Tau9_Day').innerHTML=Tau101_Day;
	document.getElementById('Tau9_Age').innerHTML=Tau101_Age;
	document.getElementById('Tau10_Reg').innerHTML=Tau102_Reg;
	document.getElementById('Tau10_AircraftType').innerHTML=Tau102_AircraftType;
	document.getElementById('Tau10_Config').innerHTML=Tau102_Config;
	document.getElementById('Tau10_Day').innerHTML=Tau102_Day;
	document.getElementById('Tau10_Age').innerHTML=Tau102_Age;
	document.getElementById('Tau11_Reg').innerHTML=Tau103_Reg;
	document.getElementById('Tau11_AircraftType').innerHTML=Tau103_AircraftType;
	document.getElementById('Tau11_Config').innerHTML=Tau103_Config;
	document.getElementById('Tau11_Day').innerHTML=Tau103_Day;
	document.getElementById('Tau11_Age').innerHTML=Tau103_Age;
	document.getElementById('Tau12_Reg').innerHTML=Tau104_Reg;
	document.getElementById('Tau12_AircraftType').innerHTML=Tau104_AircraftType;
	document.getElementById('Tau12_Config').innerHTML=Tau104_Config;
	document.getElementById('Tau12_Day').innerHTML=Tau104_Day;
	document.getElementById('Tau12_Age').innerHTML=Tau104_Age;
	document.getElementById('Tau13_Reg').innerHTML=Tau105_Reg;
	document.getElementById('Tau13_AircraftType').innerHTML=Tau105_AircraftType;
	document.getElementById('Tau13_Config').innerHTML=Tau105_Config;
	document.getElementById('Tau13_Day').innerHTML=Tau105_Day;
	document.getElementById('Tau13_Age').innerHTML=Tau105_Age;
	document.getElementById('Tau14_Reg').innerHTML=Tau106_Reg;
	document.getElementById('Tau14_AircraftType').innerHTML=Tau106_AircraftType;
	document.getElementById('Tau14_Config').innerHTML=Tau106_Config;
	document.getElementById('Tau14_Day').innerHTML=Tau106_Day;
	document.getElementById('Tau14_Age').innerHTML=Tau106_Age;
	document.getElementById('Tau15_Reg').innerHTML=Tau107_Reg;
	document.getElementById('Tau15_AircraftType').innerHTML=Tau107_AircraftType;
	document.getElementById('Tau15_Config').innerHTML=Tau107_Config;
	document.getElementById('Tau15_Day').innerHTML=Tau107_Day;
	document.getElementById('Tau15_Age').innerHTML=Tau107_Age;
	document.getElementById('Tau16_Reg').innerHTML=Tau108_Reg;
	document.getElementById('Tau16_AircraftType').innerHTML=Tau108_AircraftType;
	document.getElementById('Tau16_Config').innerHTML=Tau108_Config;
	document.getElementById('Tau16_Day').innerHTML=Tau108_Day;
	document.getElementById('Tau16_Age').innerHTML=Tau108_Age;
	document.getElementById('Tau17_Reg').innerHTML=Tau109_Reg;
	document.getElementById('Tau17_AircraftType').innerHTML=Tau109_AircraftType;
	document.getElementById('Tau17_Config').innerHTML=Tau109_Config;
	document.getElementById('Tau17_Day').innerHTML=Tau109_Day;
	document.getElementById('Tau17_Age').innerHTML=Tau109_Age;
	document.getElementById('Tau18_Reg').innerHTML=Tau110_Reg;
	document.getElementById('Tau18_AircraftType').innerHTML=Tau110_AircraftType;
	document.getElementById('Tau18_Config').innerHTML=Tau110_Config;
	document.getElementById('Tau18_Day').innerHTML=Tau110_Day;
	document.getElementById('Tau18_Age').innerHTML=Tau110_Age;
	document.getElementById('Tau19_Reg').innerHTML=Tau111_Reg;
	document.getElementById('Tau19_AircraftType').innerHTML=Tau111_AircraftType;
	document.getElementById('Tau19_Config').innerHTML=Tau111_Config;
	document.getElementById('Tau19_Day').innerHTML=Tau111_Day;
	document.getElementById('Tau19_Age').innerHTML=Tau111_Age;
	document.getElementById('Tau20_Reg').innerHTML=Tau112_Reg;
	document.getElementById('Tau20_AircraftType').innerHTML=Tau112_AircraftType;
	document.getElementById('Tau20_Config').innerHTML=Tau112_Config;
	document.getElementById('Tau20_Day').innerHTML=Tau112_Day;
	document.getElementById('Tau20_Age').innerHTML=Tau112_Age;
	document.getElementById('Tau21_Reg').innerHTML=Tau113_Reg;
	document.getElementById('Tau21_AircraftType').innerHTML=Tau113_AircraftType;
	document.getElementById('Tau21_Config').innerHTML=Tau113_Config;
	document.getElementById('Tau21_Day').innerHTML=Tau113_Day;
	document.getElementById('Tau21_Age').innerHTML=Tau113_Age;
	document.getElementById('Tau22_Reg').innerHTML=Tau114_Reg;
	document.getElementById('Tau22_AircraftType').innerHTML=Tau114_AircraftType;
	document.getElementById('Tau22_Config').innerHTML=Tau114_Config;
	document.getElementById('Tau22_Day').innerHTML=Tau114_Day;
	document.getElementById('Tau22_Age').innerHTML=Tau114_Age;
	document.getElementById('Tau23_Reg').innerHTML=Tau115_Reg;
	document.getElementById('Tau23_AircraftType').innerHTML=Tau115_AircraftType;
	document.getElementById('Tau23_Config').innerHTML=Tau115_Config;
	document.getElementById('Tau23_Day').innerHTML=Tau115_Day;
	document.getElementById('Tau23_Age').innerHTML=Tau115_Age;
	document.getElementById('Button1T').style.backgroundColor='black';
	document.getElementById('Button1T').style.color='white';
	document.getElementById('Button2T').style.backgroundColor='black';
	document.getElementById('Button2T').style.color='white';
	document.getElementById('Button3T').style.backgroundColor='black';
	document.getElementById('Button3T').style.color='white';
	document.getElementById('Button4T').style.backgroundColor='black';
	document.getElementById('Button4T').style.color='white';
	document.getElementById('Button5T').style.backgroundColor='white';
	document.getElementById('Button5T').style.color='black';
}

function XuLiTinHieu(){
	var Event1 = document.getElementById('ButtonThongTin1');
	Event1.onclick = Changelayer2;
	var Event2 = document.getElementById('ButtonThongTin2');
	Event2.onclick = Changelayer1;
	var ButtonEvent1 = document.getElementById('Button1');
	ButtonEvent1.onclick = PushBaiViet1;
	var ButtonEvent2 = document.getElementById('Button2');
	ButtonEvent2.onclick = PushBaiViet2;
	var ButtonEvent3 = document.getElementById('Button3');
	ButtonEvent3.onclick = PushBaiViet3;
	var ButtonEvent4 = document.getElementById('Button4');
	ButtonEvent4.onclick = PushBaiViet4;
	var ButtonEvent5 = document.getElementById('Button1T');
	ButtonEvent5.onclick = XULITHONGTINBANG1;
	var ButtonEvent6 = document.getElementById('Button2T');
	ButtonEvent6.onclick = XULITHONGTINBANG2;
	var ButtonEvent7 = document.getElementById('Button3T');
	ButtonEvent7.onclick = XULITHONGTINBANG3;
	var ButtonEvent8 = document.getElementById('Button4T');
	ButtonEvent8.onclick = XULITHONGTINBANG4;
	var ButtonEvent9 = document.getElementById('Button5T');
	ButtonEvent9.onclick = XULITHONGTINBANG5;
}

function Changelayer1(){
	document.getElementById('AnhVNAArea').style.display='none';
	document.getElementById('TieuDeNoiDungTrang').style.display='inherit';
	document.getElementById('ButtonThongTin2').style.display='none';
}
function Changelayer2(){
	document.getElementById('AnhVNAArea').style.display='inherit';
	document.getElementById('TieuDeNoiDungTrang').style.display='none';
	document.getElementById('ButtonThongTin2').style.display='inherit';
}

function PushBaiViet1(){
	$('#AHK1').attr("src",AHK1_address);
	$('#AHK2').attr("src",AHK2_address);
	$('#AHK3').attr("src",AHK3_address);
	$('#AHK4').attr("src",AHK4_address);
	$('#AHK5').attr("src",AHK5_address);
	$('#AHK6').attr("src",AHK6_address);
	document.getElementById('PicInfo1').innerHTML = AHK1Info;
	document.getElementById('PicInfo2').innerHTML = AHK2Info;
	document.getElementById('PicInfo3').innerHTML = AHK3Info;
	document.getElementById('PicInfo4').innerHTML = AHK4Info;
	document.getElementById('PicInfo5').innerHTML = AHK5Info;
	document.getElementById('PicInfo6').innerHTML = AHK6Info;
	document.getElementById('Button1').style.backgroundColor='white';
	document.getElementById('Button1').style.color='black';
	document.getElementById('Button2').style.backgroundColor='black';
	document.getElementById('Button2').style.color='white';
	document.getElementById('Button3').style.backgroundColor='black';
	document.getElementById('Button3').style.color='white';
	document.getElementById('Button4').style.backgroundColor='black';
	document.getElementById('Button4').style.color='white';
}

function PushBaiViet2(){
	$('#AHK1').attr("src",AHK7_address);
	$('#AHK2').attr("src",AHK8_address);
	$('#AHK3').attr("src",AHK9_address);
	$('#AHK4').attr("src",AHK10_address);
	$('#AHK5').attr("src",AHK11_address);
	$('#AHK6').attr("src",AHK12_address);
	document.getElementById('PicInfo1').innerHTML = AHK7Info;
	document.getElementById('PicInfo2').innerHTML = AHK8Info;
	document.getElementById('PicInfo3').innerHTML = AHK9Info;
	document.getElementById('PicInfo4').innerHTML = AHK10Info;
	document.getElementById('PicInfo5').innerHTML = AHK11Info;
	document.getElementById('PicInfo6').innerHTML = AHK12Info;
	document.getElementById('Button1').style.backgroundColor='black';
	document.getElementById('Button1').style.color='white';
	document.getElementById('Button2').style.backgroundColor='white';
	document.getElementById('Button2').style.color='black';
	document.getElementById('Button3').style.backgroundColor='black';
	document.getElementById('Button3').style.color='white';
	document.getElementById('Button4').style.backgroundColor='black';
	document.getElementById('Button4').style.color='white';
}

function PushBaiViet3(){
	$('#AHK1').attr("src",AHK13_address);
	$('#AHK2').attr("src",AHK14_address);
	$('#AHK3').attr("src",AHK15_address);
	$('#AHK4').attr("src",AHK16_address);
	$('#AHK5').attr("src",AHK17_address);
	$('#AHK6').attr("src",AHK18_address);
	document.getElementById('PicInfo1').innerHTML = AHK13Info;
	document.getElementById('PicInfo2').innerHTML = AHK14Info;
	document.getElementById('PicInfo3').innerHTML = AHK15Info;
	document.getElementById('PicInfo4').innerHTML = AHK16Info;
	document.getElementById('PicInfo5').innerHTML = AHK17Info;
	document.getElementById('PicInfo6').innerHTML = AHK18Info;
	document.getElementById('Button1').style.backgroundColor='black';
	document.getElementById('Button1').style.color='white';
	document.getElementById('Button2').style.backgroundColor='black';
	document.getElementById('Button2').style.color='white';
	document.getElementById('Button3').style.backgroundColor='white';
	document.getElementById('Button3').style.color='black';
	document.getElementById('Button4').style.backgroundColor='black';
	document.getElementById('Button4').style.color='white';
}

function PushBaiViet4(){
	$('#AHK1').attr("src",AHK19_address);
	$('#AHK2').attr("src",AHK20_address);
	$('#AHK3').attr("src",AHK21_address);
	$('#AHK4').attr("src",AHK22_address);
	$('#AHK5').attr("src",AHK23_address);
	$('#AHK6').attr("src",AHK24_address);
	document.getElementById('PicInfo1').innerHTML = AHK19Info;
	document.getElementById('PicInfo2').innerHTML = AHK20Info;
	document.getElementById('PicInfo3').innerHTML = AHK21Info;
	document.getElementById('PicInfo4').innerHTML = AHK22Info;
	document.getElementById('PicInfo5').innerHTML = AHK23Info;
	document.getElementById('PicInfo6').innerHTML = AHK24Info;
	document.getElementById('Button1').style.backgroundColor='black';
	document.getElementById('Button1').style.color='white';
	document.getElementById('Button2').style.backgroundColor='black';
	document.getElementById('Button2').style.color='white';
	document.getElementById('Button3').style.backgroundColor='black';
	document.getElementById('Button3').style.color='white';
	document.getElementById('Button4').style.backgroundColor='white';
	document.getElementById('Button4').style.color='black';
}